//! Fuzz-all harness: invokes every exported function that accepts caller input
//! in a multi-seed PRNG loop with adversarial scalars/strings/buffers + a pool
//! of real handles, so each is both tested (called) and fuzzed (varied inputs).
//! Buffer lengths are bounded to the real scratch, so any over-read/write is a
//! genuine library bug rather than a harness contract violation.
//!
//! Out of scope here (covered by the ordered unit tests in main_test.zig and
//! the C integration harnesses instead): lifecycle functions that destroy or
//! create shared state — startup/shutdown, the open_*/close_*/release_* and
//! *_handle_release destructors, the DLS/memory subsystem teardown, the filter
//! attribute calls that need a live filter handle, and DllMain. Looping those
//! over a shared handle pool would tear it down rather than exercise input.
const std = @import("std");
const testing = std.testing;
const openmiles = @import("openmiles");
const api_digital = @import("api/digital.zig");
const api_3d = @import("api/3d.zig");
const api_stream = @import("api/stream.zig");
const api_quick = @import("api/quick.zig");
const api_redbook = @import("api/redbook.zig");
const api_timer = @import("api/timer.zig");
const api_file = @import("api/file.zig");
const api_input = @import("api/input.zig");
const api_midi = @import("api/midi.zig");
const api_dls = @import("api/dls.zig");
const api_rib = @import("api/rib.zig");
const api_filter = @import("api/filter.zig");
const api_memory = @import("api/memory.zig");
const api_v7 = @import("api/v7.zig");
const api_v8 = @import("api/v8.zig");
const api_v9 = @import("api/v9.zig");
fn dummyTimerCb(_: u32) callconv(.winapi) void {}
const alloc = std.heap.page_allocator;
var g_scratch: [65536]u8 align(8) = [_]u8{0} ** 65536;
test "fuzz: invoke every export with adversarial inputs" {
    var prng = std.Random.DefaultPrng.init(0xF0F0F0F0);
    const rand = prng.random();
    const advf = [_]f32{ std.math.nan(f32), std.math.inf(f32), -std.math.inf(f32), -1e30, -1, 0, 0.5, 1, 1e30 };
    const advi = [_]i32{ std.math.minInt(i32), -1, 0, 1, 127, 44100, std.math.maxInt(i32) };
    const hd = openmiles.DigitalDriver.init(alloc, 44100, 16, 2) catch return;
    defer hd.deinit();
    const pcm: [64]u8 align(2) = [_]u8{0} ** 64;
    const wav = openmiles.buildWavFromPcm(alloc, &pcm, 1, 8000, 16) catch return;
    defer alloc.free(wav);
    const hm = openmiles.MidiDriver.init(alloc) catch return;
    defer hm.deinit();
    const hr = openmiles.Redbook.init(alloc, 0) catch return;
    defer hr.deinit();
    const ht_h = api_timer.AIL_register_timer(dummyTimerCb);
    const ht: ?*openmiles.Timer = if (ht_h) |t| @ptrCast(@alignCast(t)) else null;
    defer if (ht) |t| api_timer.AIL_release_timer_handle(t);
    // Sweep several PRNG seeds so the adversarial input space is explored more
    // broadly than a single fixed sequence would. Driver/timer handles above
    // are set up once and reused across all rounds.
    const seeds = [_]u64{ 0xF0F0F0F0, 0x12345678, 0xDEADBEEF, 0xCAFEBABE, 0x00000000, 0xFFFFFFFFFFFFFFFF, 0x9E3779B9, 0x1, 0x5555AAAA, 0xC0FFEE };
    for (seeds) |sd| {
        prng = std.Random.DefaultPrng.init(sd);
        var iter: usize = 0;
        while (iter < 200) : (iter += 1) {
        const rf = advf[rand.intRangeLessThan(usize, 0, advf.len)];
        const rf64: f64 = rf;
        const ri = advi[rand.intRangeLessThan(usize, 0, advi.len)];
        const ru: u32 = @bitCast(ri);
        const ru64: u64 = rand.int(u64);
        const ri64: i64 = @bitCast(ru64);
        rand.bytes(&g_scratch);
        g_scratch[g_scratch.len - 1] = 0; for (0..256) |zz| g_scratch[zz] = 0;
        const scp: *anyopaque = @ptrCast(&g_scratch);
        const rstr: [*:0]const u8 = @ptrCast(&g_scratch);
        var fo: f32 = 0;
        var io: i32 = 0;
        var uo: u32 = 0;
        var zo: usize = 0;
        var pp: ?*anyopaque = null;
        var ppnn: *anyopaque = scp;
        var prov: ?*openmiles.Provider = null;
        var pd: ?*openmiles.DigitalDriver = null;
        var pm: ?*openmiles.MidiDriver = null;
        var namep: [*:0]const u8 = rstr;
        var ps: ?*openmiles.Sample = null;
        const rz: usize = @truncate(ru64);
        const rsz: u32 = rand.intRangeAtMost(u32, 0, 256);
        const rszi: i32 = @intCast(rsz);
        var info: openmiles.AILSOUNDINFO = .{ .format = ri, .data_ptr = scp, .data_len = rand.intRangeAtMost(u32, 0, 256), .rate = ru, .bits = ri, .channels = ri, .samples = ru, .block_size = ru, .initial_ptr = null };
        std.mem.doNotOptimizeAway(.{ rf, rf64, ri, ru, ru64, ri64, scp, rstr, &fo, &io, &uo, &zo, &pp, &ppnn, &prov, &pd, &pm, &info, &namep, &ps, rz, rsz, rszi });
        // Fresh per-iteration handles so adversarial mutation can't accumulate
        // across iterations and crash a later getter.
        const hs = openmiles.Sample.init(hd) catch return;
        defer hs.deinit();
        hs.loadFromMemory(wav, false) catch {};
        const h3 = openmiles.Sample3D.init(hd) catch return;
        defer h3.deinit();
        const hq = openmiles.Sequence.init(hm) catch return;
        defer hq.deinit();
    _ = api_3d.AIL_3D_distance_factor(hd);
    _ = api_3d.AIL_3D_doppler_factor(hd);
    api_3d.AIL_3D_orientation(@as(*anyopaque, @ptrCast(h3)), &fo, &fo, &fo, &fo, &fo, &fo);
    api_3d.AIL_3D_position(@as(*anyopaque, @ptrCast(h3)), &fo, &fo, &fo);
    api_3d.AIL_3D_provider_attribute(@as(*anyopaque, @ptrCast(hd)), rstr, scp);
    _ = api_3d.AIL_3D_rolloff_factor(hd);
    _ = api_3d.AIL_3D_room_type(hd);
    api_3d.AIL_3D_sample_attribute(@as(?*anyopaque, @ptrCast(h3)), rstr, scp);
    api_3d.AIL_3D_sample_cone(@as(?*anyopaque, @ptrCast(h3)), &fo, &fo, &io);
    api_3d.AIL_3D_sample_distances(h3, &fo, &fo);
    _ = api_3d.AIL_3D_sample_effects_level(@as(?*anyopaque, @ptrCast(h3)));
    _ = api_3d.AIL_3D_sample_length(@as(?*anyopaque, @ptrCast(h3)));
    _ = api_3d.AIL_3D_sample_loop_count(@as(?*anyopaque, @ptrCast(h3)));
    api_3d.AIL_3D_sample_ms_position(@as(?*anyopaque, @ptrCast(h3)), &io, &io);
    _ = api_3d.AIL_3D_sample_obstruction(@as(?*anyopaque, @ptrCast(h3)));
    _ = api_3d.AIL_3D_sample_occlusion(@as(?*anyopaque, @ptrCast(h3)));
    _ = api_3d.AIL_3D_sample_offset(@as(?*anyopaque, @ptrCast(h3)));
    _ = api_3d.AIL_3D_sample_playback_rate(@as(?*anyopaque, @ptrCast(h3)));
    _ = api_3d.AIL_3D_sample_status(@as(?*anyopaque, @ptrCast(h3)));
    _ = api_3d.AIL_3D_sample_volume(@as(?*anyopaque, @ptrCast(h3)));
    _ = api_3d.AIL_3D_speaker_type(hd);
    _ = api_3d.AIL_3D_user_data(@as(?*anyopaque, @ptrCast(h3)), ri);
    api_3d.AIL_3D_velocity(@as(*anyopaque, @ptrCast(h3)), &fo, &fo, &fo);
    _ = api_rib.AIL_ASI_provider_attribute(prov, rstr);
    api_dls.AIL_DLS_compact(hm);
    api_dls.AIL_DLS_get_reverb(hm, &fo, &fo, &fo);
    _ = api_dls.AIL_DLS_load_file(hm, rstr, ru);
    _ = api_dls.AIL_DLS_load_memory(hm, scp, ru);
    _ = api_v7.AIL_DLS_sample_handle(hm);
    api_dls.AIL_DLS_set_reverb(hm, rf, rf, rf);
    _ = api_digital.AIL_HWND();
    _ = api_v9.AIL_IO_thread_handle(null);
    _ = api_midi.AIL_MIDI_handle_reacquire(scp);
    _ = api_digital.AIL_MMX_available();
    _ = api_digital.AIL_WAV_info(scp, scp);
    _ = api_v8.AIL_WAV_marker_by_index(null, ri, null);
    _ = api_v8.AIL_WAV_marker_by_name(null, null);
    _ = api_v8.AIL_WAV_marker_count(null);
    _ = api_midi.AIL_XMIDI_master_volume(hm);
    _ = api_3d.AIL_active_3D_sample_count(hd);
    _ = api_digital.AIL_active_sample_count(hd);
    _ = api_midi.AIL_active_sequence_count(scp);
    _ = api_v8.AIL_add_apply_environment_event_step(null, null, ri);
    _ = api_v8.AIL_add_cache_sounds_event_step(null, null, null);
    _ = api_v9.AIL_add_clear_state_event_step(null);
    _ = api_v8.AIL_add_comment_event_step(null, null);
    _ = api_v8.AIL_add_control_sounds_event_step(null, null, null, null, null, null, ri, rf, ri, ri);
    _ = api_v9.AIL_add_exec_event_event_step(null, null);
    _ = api_v8.AIL_add_persist_preset_event_step(null, null, null, null, ri);
    _ = api_v9.AIL_add_ramp_event_step(null, null, null, rf, null, ri, ri, ri);
    _ = api_v9.AIL_add_setblend_event_step(null, null, ri, null, null, null, null, null, null);
    _ = api_v8.AIL_add_sound_limit_event_step(null, null, null);
    _ = api_v8.AIL_add_start_sound_event_step(null, null, null, ri, null, null, null, null, null, null, ru, ri, ri, ri, ri, ri, null, rf, rf, rf, rf, rf, ri, ri);
    _ = api_v8.AIL_add_uncache_sounds_event_step(null, null, null);
    _ = api_3d.AIL_allocate_3D_sample_handle(hd);
    _ = api_digital.AIL_allocate_sample_handle(hd);
    _ = api_midi.AIL_allocate_sequence_handle(hm);
    _ = api_v8.AIL_apply_environment_preset(null, null, null);
    _ = api_v9.AIL_apply_raw_environment_preset(null, null);
    _ = api_v9.AIL_apply_raw_sound_preset(null, null);
    _ = api_v8.AIL_apply_sound_preset(null, null, null);
    api_stream.AIL_auto_service_stream(hs, ri);
    api_3d.AIL_auto_update_3D_position(@as(?*anyopaque, @ptrCast(h3)), ri);
    _ = api_digital.AIL_background();
    _ = api_v7.AIL_background_CPU_percent();
    api_midi.AIL_branch_index(hq, ru);
    api_v7.AIL_calculate_3D_channel_levels(hd, hs, rszi, &fo, null);
    _ = api_midi.AIL_channel_notes(hq, ri);
    _ = api_digital.AIL_compress_ADPCM(&info, &ppnn, &uo);
    _ = api_rib.AIL_compress_ASI(&info, rstr, &pp, &uo, null);
    _ = api_dls.AIL_compress_DLS(null, rstr, &pp, &uo, null);
    api_v9.AIL_configure_logging(null, ri, ri);
    _ = api_midi.AIL_controller_value(hq, ri, ri);
    _ = api_v8.AIL_create_event();
    api_v8.AIL_debug(null);
    api_v8.AIL_debug_log(null);
    _ = api_digital.AIL_decompress_ADPCM(&info, &ppnn, &uo);
    _ = api_rib.AIL_decompress_ASI(scp, rsz, rstr, &pp, &uo, null);
    api_digital.AIL_delay(rand.intRangeAtMost(u32, 0, 1)); // bounded: real sleep, don't block the fuzzer
    _ = api_digital.AIL_digital_CPU_percent(hd);
    api_digital.AIL_digital_configuration(hd, &io, &io, @as([*]u8, @ptrCast(&g_scratch)));
    _ = api_v7.AIL_digital_driver_processor(hd, ri);
    _ = api_digital.AIL_digital_handle_reacquire(hd);
    _ = api_digital.AIL_digital_latency(hd);
    api_v7.AIL_digital_master_reverb(hd, ri, &fo, &fo, &fo);
    api_v7.AIL_digital_master_reverb_levels(hd, ri, &fo, &fo);
    _ = api_digital.AIL_digital_master_volume(hd);
    _ = api_v7.AIL_digital_master_volume_level(hd);
    _ = api_v7.AIL_digital_output_filter(hd);
    api_3d.AIL_end_3D_sample(@as(?*anyopaque, @ptrCast(h3)));
    api_digital.AIL_end_sample(hs);
    api_midi.AIL_end_sequence(hq);
    _ = api_3d.AIL_enumerate_3D_provider_attributes(@as(*anyopaque, @ptrCast(hd)), &pp, &namep);
    _ = api_3d.AIL_enumerate_3D_providers(&pp, &prov, &namep);
    _ = api_3d.AIL_enumerate_3D_sample_attributes(@as(?*anyopaque, @ptrCast(h3)), &pp, &namep);
    _ = api_v7.AIL_enumerate_MP3_frames(null);
    _ = api_v8.AIL_enumerate_environment_presets(null, null, null, null);
    _ = api_v8.AIL_enumerate_events(null, null, null, null);
    _ = api_v8.AIL_enumerate_filter_properties(null, null, null);
    _ = api_v8.AIL_enumerate_filter_sample_properties(null, null, null);
    _ = api_filter.AIL_enumerate_filters(&pp, &prov, &namep);
    _ = api_v7.AIL_enumerate_output_filter_driver_attributes(null, &pp, scp);
    _ = api_v8.AIL_enumerate_output_filter_driver_properties(null, null, null);
    _ = api_v7.AIL_enumerate_output_filter_sample_attributes(null, &pp, scp);
    _ = api_v8.AIL_enumerate_output_filter_sample_properties(null, null, null);
    _ = api_v7.AIL_enumerate_sample_stage_attributes(hs, &pp, scp);
    _ = api_v8.AIL_enumerate_sample_stage_properties(null, ri, null, null);
    _ = api_v8.AIL_enumerate_sound_assets(null, null, null);
    _ = api_v8.AIL_enumerate_sound_presets(null, null, null, null);
    _ = api_dls.AIL_extract_DLS(null, rsz, &pp, &uo, &pp, &uo, null);
    api_v9.AIL_file_callbacks(null, null, null, null);
    _ = api_file.AIL_file_error();
    _ = api_v9.AIL_file_read_info(null, null, null, ru);
    _ = api_file.AIL_file_size(rstr);
    _ = api_v9.AIL_file_size_info(null, null, ru);
    _ = api_file.AIL_file_type(scp, rsz);
    _ = api_v8.AIL_file_type_named(null, null, ru);
    api_dls.AIL_filter_DLS_attribute(hm, rstr, scp);
    _ = api_dls.AIL_filter_DLS_with_XMI(null, null, &pp, &uo, ri, null);
    _ = api_v8.AIL_filter_property(null, null, null, null, null);
    api_filter.AIL_filter_sample_attribute(hs, rstr, scp);
    api_stream.AIL_filter_stream_attribute(hs, rstr, scp);
    _ = api_dls.AIL_find_DLS(null, rsz, &pp, &uo, &pp, &uo);
    _ = api_v9.AIL_find_environment_preset(null, null);
    _ = api_v7.AIL_find_filter(rstr, &prov);
    _ = api_v8.AIL_find_marker_in_list(ri, null, null);
    _ = api_v9.AIL_find_sound_preset(null, null);
    _ = api_v8.AIL_ftoa(rf, null);
    _ = api_v8.AIL_get_event_contents(null, null, null);
    _ = api_input.AIL_input_info(null);
    api_v8.AIL_get_marker_list(null, null);
    _ = api_digital.AIL_get_preference(ru);
    _ = api_v8.AIL_get_soundbank_filename(null);
    _ = api_v8.AIL_get_soundbank_mem_usage(null);
    _ = api_v9.AIL_get_soundbank_name(null);
    _ = api_v9.AIL_get_time();
    _ = api_timer.AIL_get_timer_highest_delay();
    api_v8.AIL_indent(ri);
    _ = api_v7.AIL_inspect_MP3(null, null, rszi);
    _ = api_digital.AIL_last_error();
    _ = api_dls.AIL_list_DLS(null, &pp, &uo, ri, rstr);
    _ = api_midi.AIL_list_MIDI(null, rsz, &pp, &uo, ri);
    api_v7.AIL_listener_3D_orientation(hd, &fo, &fo, &fo, &fo, &fo, &fo);
    api_v7.AIL_listener_3D_position(hd, &fo, &fo, &fo);
    api_v7.AIL_listener_3D_velocity(hd, &fo, &fo, &fo);
    _ = api_v7.AIL_listener_relative_receiver_array(hd, &io);
    api_digital.AIL_lock();
    _ = api_midi.AIL_lock_channel(hq);
    api_digital.AIL_lock_mutex();
    api_midi.AIL_map_sequence_channel(hq, ri, ri);
    _ = api_memory.AIL_mem_alloc_lock(rsz);
    _ = api_v9.AIL_mem_alloc_lock_info(ru, null, ru);
    _ = api_v8.AIL_mem_create();
    _ = api_v8.AIL_mem_create_from_existing(null, rszi);
    _ = api_v8.AIL_mem_error(null);
    _ = api_v8.AIL_mem_open(null, rszi);
    _ = api_v8.AIL_mem_pos(null);
    _ = api_v8.AIL_mem_printc(null, ri);
    _ = api_v8.AIL_mem_printf(null, null);
    _ = api_v8.AIL_mem_prints(null, null);
    _ = api_v8.AIL_mem_read(null, null, ri);
    _ = api_v8.AIL_mem_seek(null, ri);
    _ = api_v8.AIL_mem_size(null);
    api_memory.AIL_mem_use_malloc(null);
    _ = api_v8.AIL_mem_write(null, null, ri);
    _ = api_dls.AIL_merge_DLS_with_XMI(null, null, &pp, &uo);
    _ = api_midi.AIL_midiOutOpen(scp, &ppnn, ri);
    _ = api_digital.AIL_minimum_sample_buffer_size(hd, ri, ri);
    _ = api_digital.AIL_ms_count();
    _ = api_v9.AIL_ms_count64();
    _ = api_v9.AIL_ms_to_time(ru64);
    _ = api_v8.AIL_next_event_step(null, null, null, ri);
    _ = api_rib.AIL_open_ASI_provider(scp, rsz);
    _ = api_midi.AIL_open_XMIDI_driver(ru);
    _ = api_digital.AIL_open_digital_driver(ru, ri, ri, ru);
    _ = api_filter.AIL_open_filter(prov, hd);
    _ = api_midi.AIL_open_midi_driver(ru);
    _ = api_v8.AIL_open_soundbank(null, null);
    api_v7.AIL_output_filter_driver_attribute(null, rstr, scp);
    _ = api_v8.AIL_output_filter_driver_property(null, null, null, null, null);
    api_digital.AIL_pause_sample(hs);
    api_midi.AIL_pause_sequence(hq);
    api_stream.AIL_pause_stream(hs, ri);
    _ = api_v8.AIL_platform_property(null, ri, null, null, null);
    _ = api_digital.AIL_primary_digital_driver(hd);
    api_quick.AIL_quick_halt(hs);
    api_quick.AIL_quick_handles(&ps, &pd, &pm);
    _ = api_quick.AIL_quick_ms_length(hs);
    _ = api_quick.AIL_quick_ms_position(hs);
    api_quick.AIL_quick_play(hs, ri);
    api_v7.AIL_quick_set_low_pass_cut_off(hs, ri, rf);
    api_quick.AIL_quick_set_ms_position(hs, ri);
    api_quick.AIL_quick_set_reverb(hs, rf, rf, rf);
    api_v7.AIL_quick_set_reverb_levels(hs, rf, rf);
    api_quick.AIL_quick_set_speed(hs, ri);
    api_quick.AIL_quick_set_volume(hs, ri, ri);
    _ = api_quick.AIL_quick_status(hs);
    api_quick.AIL_quick_stop(hs);
    _ = api_quick.AIL_quick_type(hs);
    _ = api_redbook.AIL_redbook_eject(hr);
    _ = api_redbook.AIL_redbook_id(hr);
    _ = api_redbook.AIL_redbook_open(ru);
    _ = api_redbook.AIL_redbook_open_drive(ri);
    _ = api_redbook.AIL_redbook_pause(hr);
    _ = api_redbook.AIL_redbook_play(hr, ru, ru);
    _ = api_redbook.AIL_redbook_position(hr);
    _ = api_redbook.AIL_redbook_resume(hr);
    _ = api_redbook.AIL_redbook_retract(hr);
    api_redbook.AIL_redbook_set_volume(hr, ri);
    api_v7.AIL_redbook_set_volume_level(hr, rf);
    _ = api_redbook.AIL_redbook_status(hr);
    _ = api_redbook.AIL_redbook_stop(hr);
    _ = api_redbook.AIL_redbook_track(hr);
    api_redbook.AIL_redbook_track_info(hr, ru, &uo, &uo);
    _ = api_redbook.AIL_redbook_tracks(hr);
    _ = api_redbook.AIL_redbook_volume(hr);
    _ = api_v7.AIL_redbook_volume_level(hr);
    _ = api_3d.AIL_register_3D_EOS_callback(@as(?*anyopaque, @ptrCast(h3)), null);
    _ = api_digital.AIL_register_EOB_callback(hs, null);
    _ = api_stream.AIL_register_EOF_callback(hs, null);
    _ = api_digital.AIL_register_EOS_callback(hs, null);
    api_midi.AIL_register_ICA_array(hq, scp);
    _ = api_digital.AIL_register_SOB_callback(hs, null);
    _ = api_midi.AIL_register_beat_callback(hq, null);
    _ = api_midi.AIL_register_event_callback(hm, null);
    api_v8.AIL_register_falloff_function_callback(null, ri);
    _ = api_midi.AIL_register_prefix_callback(hq, null);
    _ = api_midi.AIL_register_sequence_callback(hq, null);
    _ = api_stream.AIL_register_stream_callback(hs, null);
    _ = api_midi.AIL_register_timbre_callback(hm, null);
    api_v8.AIL_register_trace_callback(null);
    _ = api_midi.AIL_register_trigger_callback(hq, null);
    api_rib.AIL_request_EOB_ASI_reset(hs, ru, ri);
    _ = api_v9.AIL_resolve_raw_environment_preset(null, ri);
    _ = api_v9.AIL_resolve_raw_sound_preset(null, null, ri);
    api_3d.AIL_resume_3D_sample(@as(?*anyopaque, @ptrCast(h3)));
    api_digital.AIL_resume_sample(hs);
    api_midi.AIL_resume_sequence(hq);
    _ = api_v7.AIL_room_type(hd, ri);
    api_v7.AIL_sample_3D_cone(hs, &fo, &fo, &fo);
    api_v7.AIL_sample_3D_distances(hs, &fo, &fo, &io);
    api_v7.AIL_sample_3D_orientation(hs, &fo, &fo, &fo, &fo, &fo, &fo);
    api_v7.AIL_sample_3D_position(hs, &fo, &fo, &fo);
    api_v7.AIL_sample_3D_velocity(hs, &fo, &fo, &fo);
    api_v8.AIL_sample_51_volume_levels(null, null, null, null, null, null, null);
    api_v8.AIL_sample_51_volume_pan(null, null, null, null, null, null);
    _ = api_v8.AIL_sample_buffer_available(null);
    _ = api_v8.AIL_sample_buffer_count(null);
    _ = api_digital.AIL_sample_buffer_info(hs, ri, &uo, &uo, &uo, &uo);
    _ = api_digital.AIL_sample_buffer_ready(hs);
    _ = api_v8.AIL_sample_channel_count(null, null);
    api_v7.AIL_sample_channel_levels(hs, null, null, &fo, rszi);
    _ = api_v7.AIL_sample_exclusion(hs);
    _ = api_digital.AIL_sample_granularity(hd);
    _ = api_v9.AIL_sample_loaded_len(null);
    _ = api_v8.AIL_sample_loop_block(null, null, null);
    _ = api_digital.AIL_sample_loop_count(hs);
    _ = api_v7.AIL_sample_low_pass_cut_off(hs, ri);
    _ = api_v9.AIL_sample_ms_lookup(null, ri, null);
    api_digital.AIL_sample_ms_position(hs, &io, &io);
    _ = api_v7.AIL_sample_obstruction(hs);
    _ = api_v7.AIL_sample_occlusion(hs);
    _ = api_v8.AIL_sample_output_levels(null, null, null, null, ri);
    _ = api_digital.AIL_sample_pan(hs);
    _ = api_v8.AIL_sample_playback_delay(null);
    _ = api_digital.AIL_sample_playback_rate(hs);
    _ = api_v8.AIL_sample_playback_rate_factor(hs);
    _ = api_digital.AIL_sample_position(hs);
    _ = api_v7.AIL_sample_processor(hs, ri);
    api_digital.AIL_sample_reverb(hs, &fo, &fo, &fo);
    api_v7.AIL_sample_reverb_levels(hs, &fo, &fo);
    api_v8.AIL_sample_speaker_scale_factors(null, null, null, ri);
    api_v7.AIL_sample_stage_attribute(hs, rstr, scp);
    _ = api_v8.AIL_sample_stage_property(null, ri, null, ri, null, null, null);
    _ = api_digital.AIL_sample_status(hs);
    _ = api_digital.AIL_sample_user_data(hs, ri);
    _ = api_digital.AIL_sample_volume(hs);
    api_v7.AIL_sample_volume_levels(hs, &fo, &fo);
    api_v7.AIL_sample_volume_pan(hs, &fo, &fo);
    api_midi.AIL_send_channel_voice_message(hm, hq, ri, ri, ri);
    api_midi.AIL_send_sysex_message(hq, scp);
    _ = api_midi.AIL_sequence_loop_count(hq);
    api_midi.AIL_sequence_ms_position(hq, &io, &io);
    api_midi.AIL_sequence_position(hq, &io, &io);
    _ = api_midi.AIL_sequence_status(hq);
    _ = api_midi.AIL_sequence_tempo(hq);
    _ = api_midi.AIL_sequence_user_data(hq, ri);
    _ = api_midi.AIL_sequence_volume(hq);
    api_digital.AIL_serve();
    _ = api_stream.AIL_service_stream(hs, ri);
    api_3d.AIL_set_3D_distance_factor(hd, rf);
    api_3d.AIL_set_3D_doppler_factor(hd, rf);
    api_3d.AIL_set_3D_orientation(@as(?*anyopaque, @ptrCast(h3)), rf, rf, rf, rf, rf, rf);
    api_3d.AIL_set_3D_position(@as(?*anyopaque, @ptrCast(h3)), rf, rf, rf);
    api_3d.AIL_set_3D_provider_preference(@as(*anyopaque, @ptrCast(hd)), rstr, scp);
    api_3d.AIL_set_3D_rolloff_factor(hd, rf);
    api_3d.AIL_set_3D_room_type(hd, ri);
    api_3d.AIL_set_3D_sample_cone(@as(?*anyopaque, @ptrCast(h3)), rf, rf, ri);
    api_3d.AIL_set_3D_sample_distances(@as(?*anyopaque, @ptrCast(h3)), rf, rf);
    api_3d.AIL_set_3D_sample_effects_level(@as(?*anyopaque, @ptrCast(h3)), rf);
    api_3d.AIL_set_3D_sample_loop_block(@as(?*anyopaque, @ptrCast(h3)), ri, ri);
    api_3d.AIL_set_3D_sample_loop_count(@as(?*anyopaque, @ptrCast(h3)), rszi);
    api_3d.AIL_set_3D_sample_ms_position(@as(?*anyopaque, @ptrCast(h3)), ri);
    api_3d.AIL_set_3D_sample_obstruction(@as(?*anyopaque, @ptrCast(h3)), rf);
    api_3d.AIL_set_3D_sample_occlusion(@as(?*anyopaque, @ptrCast(h3)), rf);
    api_3d.AIL_set_3D_sample_offset(@as(?*anyopaque, @ptrCast(h3)), ru);
    api_3d.AIL_set_3D_sample_playback_rate(@as(?*anyopaque, @ptrCast(h3)), ri);
    api_3d.AIL_set_3D_sample_preference(@as(?*anyopaque, @ptrCast(h3)), rstr, scp);
    api_3d.AIL_set_3D_sample_volume(@as(?*anyopaque, @ptrCast(h3)), ri);
    api_3d.AIL_set_3D_speaker_type(hd, ri);
    api_3d.AIL_set_3D_user_data(@as(?*anyopaque, @ptrCast(h3)), ri, ru);
    api_3d.AIL_set_3D_velocity(@as(?*anyopaque, @ptrCast(h3)), rf, rf, rf, rf);
    api_3d.AIL_set_3D_velocity_vector(@as(?*anyopaque, @ptrCast(h3)), rf, rf, rf);
    _ = api_dls.AIL_set_DLS_processor(hm, ri, null);
    api_digital.AIL_set_DirectSound_HWND(hd, scp);
    api_midi.AIL_set_XMIDI_master_volume(hm, ri);
    _ = api_digital.AIL_set_digital_driver_processor(hd, ri, null);
    api_v7.AIL_set_digital_master_reverb(hd, ri, rf, rf, rf);
    api_v7.AIL_set_digital_master_reverb_levels(hd, ri, rf, rf);
    api_digital.AIL_set_digital_master_volume(hd, ri);
    api_v7.AIL_set_digital_master_volume_level(hd, rf);
    api_digital.AIL_set_error(rstr);
    api_file.AIL_set_file_async_callbacks(null, null, null, null, null);
    api_file.AIL_set_file_callbacks(null, null, null, null);
    api_dls.AIL_set_filter_DLS_preference(hm, rstr, scp);
    api_filter.AIL_set_filter_sample_preference(hs, rstr, scp);
    api_stream.AIL_set_filter_stream_preference(hs, rstr, scp);
    api_input.AIL_set_input_state(null, ri);
    api_3d.AIL_set_listener_3D_orientation(hd, rf, rf, rf, rf, rf, rf);
    api_3d.AIL_set_listener_3D_position(hd, rf, rf, rf);
    api_3d.AIL_set_listener_3D_velocity(hd, rf, rf, rf, rf);
    api_v7.AIL_set_listener_3D_velocity_vector(hd, rf, rf, rf);
    api_v7.AIL_set_listener_relative_receiver_array(hd, null, ri);
    api_memory.AIL_set_mem_callbacks(null, null);
    api_v7.AIL_set_output_filter_driver_preference(null, rstr, scp);
    _ = api_digital.AIL_set_preference(ru, ri);
    api_digital.AIL_set_redist_directory(rstr);
    api_v7.AIL_set_room_type(hd, ri, ri);
    api_v7.AIL_set_sample_3D_cone(hs, rf, rf, rf);
    api_v7.AIL_set_sample_3D_distances(hs, rf, rf, ri);
    api_v7.AIL_set_sample_3D_orientation(hs, rf, rf, rf, rf, rf, rf);
    api_v7.AIL_set_sample_3D_position(hs, rf, rf, rf);
    api_v7.AIL_set_sample_3D_velocity(hs, rf, rf, rf, rf);
    api_v7.AIL_set_sample_3D_velocity_vector(hs, rf, rf, rf);
    api_v8.AIL_set_sample_51_volume_levels(hs, rf, rf, rf, rf, rf, rf);
    api_v8.AIL_set_sample_51_volume_pan(hs, rf, rf, rf, rf, rf);
    api_digital.AIL_set_sample_adpcm_block_size(hs, ru);
    _ = api_v8.AIL_set_sample_buffer_count(null, ri);
    api_v7.AIL_set_sample_channel_levels(hs, null, null, &fo, rszi);
    api_v7.AIL_set_sample_exclusion(hs, rf);
    api_v8.AIL_set_sample_is_3D(hs, ri);
    api_digital.AIL_set_sample_loop_block(hs, ri, ri);
    api_digital.AIL_set_sample_loop_count(hs, rszi);
    api_v7.AIL_set_sample_low_pass_cut_off(hs, ri, rf);
    api_digital.AIL_set_sample_ms_position(hs, ri);
    api_v7.AIL_set_sample_obstruction(hs, rf);
    api_v7.AIL_set_sample_occlusion(hs, rf);
    api_digital.AIL_set_sample_pan(hs, ri);
    api_v8.AIL_set_sample_playback_delay(null, ri);
    api_digital.AIL_set_sample_playback_rate(hs, ri);
    api_v8.AIL_set_sample_playback_rate_factor(hs, rf);
    api_digital.AIL_set_sample_position(hs, ru);
    _ = api_digital.AIL_set_sample_processor(hs, ri, null);
    api_digital.AIL_set_sample_reverb(hs, rf, rf, rf);
    api_v7.AIL_set_sample_reverb_levels(hs, rf, rf);
    api_v8.AIL_set_sample_speaker_scale_factors(null, null, null, ri);
    api_v7.AIL_set_sample_stage_preference(hs, rstr, scp);
    api_digital.AIL_set_sample_type(hs, ru, ru);
    api_digital.AIL_set_sample_user_data(hs, ri, ru);
    api_digital.AIL_set_sample_volume(hs, ri);
    api_v7.AIL_set_sample_volume_levels(hs, rf, rf);
    api_digital.AIL_set_sample_volume_pan(hs, ri, ri);
    api_midi.AIL_set_sequence_loop_count(hq, rszi);
    api_midi.AIL_set_sequence_ms_position(hq, ri);
    api_midi.AIL_set_sequence_tempo(hq, ri, ri);
    api_midi.AIL_set_sequence_user_data(hq, ri, ru);
    api_midi.AIL_set_sequence_volume(hq, ri, ri);
    api_v7.AIL_set_speaker_configuration(hd, null, ri, rf);
    api_v7.AIL_set_speaker_reverb_levels(hd, &fo, &fo, null, rszi);
    api_stream.AIL_set_stream_loop_block(hs, ri, ri);
    api_stream.AIL_set_stream_loop_count(hs, rszi);
    api_stream.AIL_set_stream_ms_position(hs, ri);
    api_stream.AIL_set_stream_pan(hs, ri);
    api_stream.AIL_set_stream_playback_rate(hs, ri);
    api_stream.AIL_set_stream_position(hs, ru);
    _ = api_stream.AIL_set_stream_processor(hs, ri, null);
    api_stream.AIL_set_stream_reverb(hs, rf, rf, rf);
    api_stream.AIL_set_stream_user_data(hs, ri, ru);
    api_stream.AIL_set_stream_volume(hs, ri);
    api_timer.AIL_set_timer_divisor(ht, ru);
    api_timer.AIL_set_timer_frequency(ht, ru);
    api_timer.AIL_set_timer_period(ht, ru);
    api_timer.AIL_set_timer_user(ht, ru);
    api_timer.AIL_set_timer_user_data(ht, ru);
    api_v9.AIL_sleep(rand.intRangeAtMost(u32, 0, 1)); // bounded: real sleep, don't block the fuzzer
    api_v8.AIL_sound_asset_filename(null, ri);
    _ = api_v9.AIL_sound_asset_info(null, null, null, null);
    api_v7.AIL_speaker_configuration(hd, &io, &io, &fo, null);
    api_3d.AIL_start_3D_sample(@as(?*anyopaque, @ptrCast(h3)));
    api_timer.AIL_start_all_timers();
    api_digital.AIL_start_sample(hs);
    api_midi.AIL_start_sequence(hq);
    api_stream.AIL_start_stream(hs);
    api_timer.AIL_start_timer(ht);
    api_3d.AIL_stop_3D_sample(@as(?*anyopaque, @ptrCast(h3)));
    api_timer.AIL_stop_all_timers();
    api_digital.AIL_stop_sample(hs);
    api_midi.AIL_stop_sequence(hq);
    api_timer.AIL_stop_timer(ht);
    _ = api_v9.AIL_stream_filled_percent(null);
    api_stream.AIL_stream_info(hs, &io, &io, &io, &io);
    _ = api_stream.AIL_stream_loop_count(hs);
    api_stream.AIL_stream_ms_position(hs, &io, &io);
    _ = api_stream.AIL_stream_pan(hs);
    _ = api_stream.AIL_stream_playback_rate(hs);
    _ = api_stream.AIL_stream_position(hs);
    api_stream.AIL_stream_reverb(hs, &fo, &fo, &fo);
    _ = api_v7.AIL_stream_sample_handle(hs);
    _ = api_stream.AIL_stream_status(hs);
    _ = api_stream.AIL_stream_user_data(hs, ri);
    _ = api_stream.AIL_stream_volume(hs);
    _ = api_v8.AIL_stricmp(null, null);
    _ = api_v8.AIL_strnicmp(null, null, ru);
    api_v8.AIL_sys_debug(null);
    _ = api_v9.AIL_time_to_ms(ru64);
    _ = api_v9.AIL_timer_thread_handle(null);
    _ = api_midi.AIL_true_sequence_channel(hq, ri);
    _ = api_v8.AIL_unapply_environment_preset(null, null, null);
    _ = api_v9.AIL_unapply_raw_environment_preset(null, null);
    _ = api_v9.AIL_unapply_raw_sound_preset(null, null);
    _ = api_v8.AIL_unapply_sound_preset(null, null, null);
    api_digital.AIL_unlock();
    api_digital.AIL_unlock_mutex();
    api_3d.AIL_update_3D_position(@as(?*anyopaque, @ptrCast(h3)), rf);
    api_v7.AIL_update_listener_3D_position(hd, rf);
    api_v7.AIL_update_sample_3D_position(hs, rf);
    _ = api_digital.AIL_us_count();
    _ = api_v9.AIL_us_count64();
    _ = api_digital.AIL_waveOutOpen(&pd, &uo, ri, null);
    api_dls.DLSCompactMemory(hm);
    _ = api_dls.DLSLoadFile(hm, rstr, ru);
    _ = api_dls.DLSLoadMemFile(hm, scp, ru);
    _ = api_dls.DLSMSSGetCPU(hm);
    _ = api_dls.DLSMSSOpen(hd, hq, null, ru, ri, ri, ru);
    api_dls.DLSSetAttribute(hm, rstr, scp);
    _ = api_digital.DllMain(scp, ru, null);
    _ = api_v7.RIB_MAIN(null, rstr);
    _ = api_rib.RIB_alloc_provider_handle(scp);
    _ = api_rib.RIB_enumerate_providers(rstr, &pp, &prov);
    _ = api_rib.RIB_error();
    _ = api_rib.RIB_find_file_dec_provider(rstr, rstr, rstr, rstr, rstr);
    _ = api_rib.RIB_find_file_provider(rstr, rstr, rstr);
    _ = api_rib.RIB_find_files_provider(rstr, rstr, rstr, rstr, rstr);
    _ = api_rib.RIB_find_provider(rstr, rstr, rstr);
    _ = api_rib.RIB_load_application_providers(rstr);
    _ = api_rib.RIB_load_provider_library(rstr);
    _ = api_v7.RIB_load_static_provider_library(null, rstr);
    _ = api_rib.RIB_provider_library_handle();
    _ = api_rib.RIB_provider_system_data(prov, ru);
    _ = api_rib.RIB_provider_user_data(prov, ru);
    api_rib.RIB_register_interface(prov, rstr, rszi, scp);
    _ = api_rib.RIB_request_interface(prov, rstr, rszi, scp);
    _ = api_rib.RIB_request_interface_entry(prov, rstr, rstr, &zo);
    api_rib.RIB_set_provider_system_data(prov, ru, rz);
    api_rib.RIB_set_provider_user_data(prov, ru, rz);
    _ = api_rib.RIB_type_string(ru);
    api_rib.RIB_unregister_interface(prov, rstr, rszi, scp);
    // Input validators that load/parse caller-supplied buffers. Buffer lengths
    // are bounded to the real scratch (rsz <= 256, well inside g_scratch's
    // 64 KiB) so any out-of-bounds read/write is a genuine library bug, not a
    // harness contract violation. Filenames resolve to "" (scratch starts
    // zeroed), so the file writers just fail to open rather than touching disk.
    var pfo: ?*f32 = null;
    var pco: ?*const anyopaque = null;
    _ = api_digital.AIL_set_sample_file(hs, scp, ri);
    api_digital.AIL_set_sample_address(hs, scp, rsz);
    api_v7.AIL_set_sample_info(hs, &info);
    _ = api_digital.AIL_set_named_sample_file(hs, rstr, scp, rszi, ru);
    _ = api_3d.AIL_set_3D_sample_file(@as(?*anyopaque, @ptrCast(h3)), scp);
    _ = api_3d.AIL_set_3D_sample_info(@as(?*anyopaque, @ptrCast(h3)), @as(?*anyopaque, &info));
    api_digital.AIL_load_sample_buffer(hs, ru, scp, rsz);
    _ = api_digital.AIL_size_processed_digital_audio(ru, ru, rszi, &info);
    _ = api_digital.AIL_process_digital_audio(hd, scp, rsz, scp, rsz, ru);
    _ = api_dls.AIL_DLS_get_info(hm, scp, scp);
    _ = api_digital.AIL_get_DirectSound_info(hd, scp, rsz);
    api_v7.AIL_speaker_reverb_levels(hd, &pfo, &pfo, &pco);
    _ = api_file.AIL_file_read(rstr, scp);
    _ = api_file.AIL_file_write(rstr, scp, rsz);
    _ = api_digital.AIL_WAV_file_write(rstr, scp, rsz, ri, ri);
    _ = api_midi.AIL_MIDI_to_XMI(scp, rsz, null, &uo, ru);
    // More memory parsers fed adversarial (zeroed-prefix) buffers.
    if (api_quick.AIL_quick_load_mem(scp, rsz)) |qs| qs.deinit();
    api_digital.AIL_init_sample(hs);
    _ = api_midi.AIL_init_sequence(hq, scp, ri);
    _ = api_dls.DLSGetInfo(hm, scp, scp);
    _ = api_dls.DLSLoadMemFile(hm, scp, ru);
    var rib_entry: openmiles.RIB_INTERFACE_ENTRY = undefined;
    _ = api_rib.RIB_enumerate_interface(prov, rstr, ru, &pp, &rib_entry);
        }
    }
}
