//! DLL entry point: root module of the mss32 shared library.
//!
//! This file owns the pieces that exist only because the project builds a
//! Windows DLL:
//!   * DllMain, and
//!   * the PE export table — the comptime `@export` loop below resolves every
//!     decorated stdcall name (`_AIL_init_sample@8`, ...) against its
//!     implementation across the api/*.zig modules, gated per entry by
//!     `.ver`/`.ver_max` so each -Dmss-version build ships that release's
//!     exact export set.
//!
//! No other state lives here — shared state is in root.zig (the `openmiles`
//! module) to keep the dependency graph one-way:
//!   main.zig  -->  api/*.zig  -->  openmiles (root.zig)

const std = @import("std");
const builtin = @import("builtin");
const openmiles = @import("openmiles");

pub fn DllMain(hinstDLL: *anyopaque, fdwReason: u32, lpvReserved: ?*anyopaque) callconv(.winapi) std.os.windows.BOOL {
    _ = hinstDLL;
    _ = fdwReason;
    _ = lpvReserved;
    // BOOL is a non-exclusive enum in Zig 0.16, not an integer; .TRUE is its
    // canonical truthy value.
    return .TRUE;
}
comptime {
    @setEvalBranchQuota(1000000);
    const is_x86_windows = builtin.target.cpu.arch == .x86 and builtin.target.os.tag == .windows;
    if (is_x86_windows) {
        const Target = struct {
            name: []const u8,
            stack_size: u8,
            ver: u16 = 30, // MSS version (major*10+minor) the export first appeared in
            ver_max: u16 = 999, // last version that still exports it (for renamed/dropped APIs)
            // Optional COFF symbol to alias when it differs from `name` (e.g. a
            // renamed export sharing another function's implementation).
            symbol: ?[]const u8 = null,
            // The real DLL exports the public RIB-interface and DLS APIs under
            // __cdecl (undecorated: no leading `_`, no `@N`), while the AIL_*
            // surface and the RIB provider-management calls stay __stdcall. When
            // set, emit the bare name and the backing fn must be callconv(.c).
            cdecl: bool = false,
        };
        const targets = [_]Target{
            .{ .name = "AIL_startup", .stack_size = 0 },
            .{ .name = "AIL_shutdown", .stack_size = 0 },
            .{ .name = "AIL_set_redist_directory", .stack_size = 4, .ver = 60 },
            .{ .name = "AIL_last_error", .stack_size = 0 },
            .{ .name = "AIL_get_preference", .stack_size = 4 },
            .{ .name = "AIL_set_preference", .stack_size = 8 },
            .{ .name = "AIL_open_midi_driver", .stack_size = 4 },
            .{ .name = "AIL_close_midi_driver", .stack_size = 4 },
            .{ .name = "AIL_open_XMIDI_driver", .stack_size = 4, .ver = 61, .ver_max = 70 },
            .{ .name = "AIL_close_XMIDI_driver", .stack_size = 4, .ver = 61, .ver_max = 70 },
            .{ .name = "AIL_allocate_sequence_handle", .stack_size = 4, .ver_max = 70 },
            .{ .name = "AIL_release_sequence_handle", .stack_size = 4, .ver_max = 70 },
            .{ .name = "AIL_init_sequence", .stack_size = 12, .ver_max = 70 },
            .{ .name = "AIL_start_sequence", .stack_size = 4, .ver_max = 70 },
            .{ .name = "AIL_stop_sequence", .stack_size = 4, .ver_max = 70 },
            .{ .name = "AIL_pause_sequence", .stack_size = 4 },
            .{ .name = "AIL_resume_sequence", .stack_size = 4, .ver_max = 70 },
            .{ .name = "AIL_sequence_status", .stack_size = 4, .ver_max = 70 },
            .{ .name = "AIL_set_sequence_volume", .stack_size = 12, .ver_max = 70 },
            .{ .name = "AIL_set_sequence_loop_count", .stack_size = 8, .ver_max = 70 },
            .{ .name = "AIL_branch_index", .stack_size = 8, .ver_max = 70 },
            .{ .name = "AIL_DLS_load_file", .stack_size = 12, .ver = 50, .ver_max = 70 },
            .{ .name = "AIL_DLS_unload_file", .stack_size = 8 },
            .{ .name = "AIL_digital_handle_release", .stack_size = 4 },
            .{ .name = "AIL_digital_handle_reacquire", .stack_size = 4 },
            .{ .name = "AIL_waveOutOpen", .stack_size = 16, .ver_max = 66 },
            .{ .name = "AIL_open_digital_driver", .stack_size = 16, .ver = 61 },
            .{ .name = "AIL_close_digital_driver", .stack_size = 4, .ver = 61 },
            .{ .name = "AIL_serve", .stack_size = 0 },
            .{ .name = "AIL_set_digital_master_volume", .stack_size = 8, .ver_max = 61 },
            .{ .name = "AIL_digital_master_volume", .stack_size = 4, .ver_max = 61 },
            .{ .name = "AIL_allocate_sample_handle", .stack_size = 4 },
            .{ .name = "AIL_release_sample_handle", .stack_size = 4 },
            // init_sample arity by era: v3-v6 @4 (S), v7 @12 (S + 2 extra slots),
            // v8+ @8 (S, format).
            .{ .name = "AIL_init_sample", .stack_size = 4, .ver_max = 66 },
            .{ .name = "AIL_init_sample", .stack_size = 12, .ver = 70, .ver_max = 70, .symbol = "AIL_init_sample_v7" },
            .{ .name = "AIL_init_sample", .stack_size = 8, .ver = 80, .symbol = "AIL_init_sample_v8" },
            .{ .name = "AIL_set_named_sample_file", .stack_size = 20, .ver = 50 },
            .{ .name = "AIL_set_sample_file", .stack_size = 12 },
            .{ .name = "AIL_set_sample_address", .stack_size = 12 },
            .{ .name = "AIL_set_sample_type", .stack_size = 12, .ver_max = 66 },
            .{ .name = "AIL_start_sample", .stack_size = 4 },
            .{ .name = "AIL_stop_sample", .stack_size = 4 },
            .{ .name = "AIL_pause_sample", .stack_size = 4 },
            .{ .name = "AIL_resume_sample", .stack_size = 4 },
            .{ .name = "AIL_end_sample", .stack_size = 4 },
            .{ .name = "AIL_sample_status", .stack_size = 4 },
            .{ .name = "AIL_sample_volume", .stack_size = 4, .ver_max = 61 },
            .{ .name = "AIL_sample_pan", .stack_size = 4, .ver_max = 61 },
            .{ .name = "AIL_sample_playback_rate", .stack_size = 4 },
            .{ .name = "AIL_set_sample_volume", .stack_size = 8, .ver_max = 61 },
            .{ .name = "AIL_set_sample_pan", .stack_size = 8, .ver_max = 61 },
            .{ .name = "AIL_set_sample_playback_rate", .stack_size = 8 },
            .{ .name = "AIL_set_sample_volume_pan", .stack_size = 12, .ver = 65 },
            .{ .name = "AIL_set_sample_loop_count", .stack_size = 8 },
            .{ .name = "AIL_active_sample_count", .stack_size = 4 },
            .{ .name = "AIL_sample_ms_position", .stack_size = 12, .ver = 50 },
            .{ .name = "AIL_set_sample_ms_position", .stack_size = 8, .ver = 50 },
            .{ .name = "AIL_sample_position", .stack_size = 4 },
            .{ .name = "AIL_set_sample_position", .stack_size = 8 },
            .{ .name = "AIL_sample_loop_count", .stack_size = 4 },
            .{ .name = "AIL_register_EOS_callback", .stack_size = 8 },
            .{ .name = "AIL_open_stream", .stack_size = 12 },
            // Undocumented internal that leaked into the 6.1a export table only.
            .{ .name = "AIL_open_stream_by_sample", .stack_size = 16, .ver = 61, .ver_max = 61 },
            .{ .name = "AIL_close_stream", .stack_size = 4 },
            .{ .name = "AIL_start_stream", .stack_size = 4 },
            .{ .name = "AIL_pause_stream", .stack_size = 8 },
            .{ .name = "AIL_set_stream_volume", .stack_size = 8, .ver_max = 61 },
            .{ .name = "AIL_set_stream_loop_count", .stack_size = 8 },
            .{ .name = "AIL_register_stream_callback", .stack_size = 8 },
            .{ .name = "AIL_auto_service_stream", .stack_size = 8 },
            .{ .name = "AIL_set_stream_playback_rate", .stack_size = 8, .ver_max = 66 },
            .{ .name = "AIL_set_stream_pan", .stack_size = 8, .ver_max = 61 },
            // Combined F32 volume/pan stream setter — present in many v4+ builds
            // (e.g. Midnight Club II's v6 mss32.dll) though absent from some refs.
            .{ .name = "AIL_set_stream_volume_pan", .stack_size = 12, .ver = 65, .ver_max = 66 },
            .{ .name = "AIL_set_stream_ms_position", .stack_size = 8, .ver = 50 },
            .{ .name = "AIL_stream_status", .stack_size = 4 },
            .{ .name = "AIL_stream_playback_rate", .stack_size = 4, .ver_max = 66 },
            .{ .name = "AIL_stream_volume", .stack_size = 4, .ver_max = 61 },
            .{ .name = "AIL_stream_pan", .stack_size = 4, .ver_max = 61 },
            .{ .name = "AIL_stream_loop_count", .stack_size = 4 },
            .{ .name = "AIL_stream_ms_position", .stack_size = 12, .ver = 50 },
            .{ .name = "RIB_alloc_provider_handle", .stack_size = 4, .ver = 40, .cdecl = true, .ver_max = 79 },
            .{ .name = "RIB_alloc_provider_handle", .stack_size = 4, .ver = 80, .symbol = "RIB_alloc_provider_handle_std" },
            .{ .name = "RIB_free_provider_handle", .stack_size = 4, .ver = 40, .cdecl = true, .ver_max = 79 },
            .{ .name = "RIB_free_provider_handle", .stack_size = 4, .ver = 80, .symbol = "RIB_free_provider_handle_std" },
            .{ .name = "RIB_register_interface", .stack_size = 16, .ver = 40, .cdecl = true, .ver_max = 79 },
            .{ .name = "RIB_register_interface", .stack_size = 16, .ver = 80, .symbol = "RIB_register_interface_std" },
            .{ .name = "RIB_unregister_interface", .stack_size = 16, .ver = 40, .cdecl = true, .ver_max = 79 },
            .{ .name = "RIB_unregister_interface", .stack_size = 16, .ver = 80, .symbol = "RIB_unregister_interface_std" },
            .{ .name = "RIB_provider_library_handle", .stack_size = 0, .ver = 50, .ver_max = 61 },
            .{ .name = "RIB_load_application_providers", .stack_size = 4, .ver = 50 },
            .{ .name = "RIB_enumerate_providers", .stack_size = 12, .ver = 50 },
            .{ .name = "RIB_request_interface", .stack_size = 16, .ver = 40, .cdecl = true, .ver_max = 79 },
            .{ .name = "RIB_request_interface", .stack_size = 16, .ver = 80, .symbol = "RIB_request_interface_std" },
            .{ .name = "RIB_find_files_provider", .stack_size = 20, .ver = 60 },
            .{ .name = "AIL_open_filter", .stack_size = 8, .ver = 60 },
            .{ .name = "AIL_close_filter", .stack_size = 4, .ver = 60 },
            .{ .name = "AIL_set_sample_filter", .stack_size = 12, .ver = 60 },
            .{ .name = "AIL_filter_attribute", .stack_size = 12, .ver = 60, .ver_max = 66 },
            .{ .name = "AIL_set_filter_attribute", .stack_size = 12, .ver = 60 },
            .{ .name = "AIL_enumerate_filters", .stack_size = 12, .ver = 60 },
            .{ .name = "AIL_enumerate_3D_providers", .stack_size = 12, .ver = 50, .ver_max = 66 },
            .{ .name = "AIL_allocate_3D_sample_handle", .stack_size = 4, .ver = 50, .ver_max = 66 },
            .{ .name = "AIL_release_3D_sample_handle", .stack_size = 4, .ver = 50, .ver_max = 66 },
            .{ .name = "AIL_set_3D_sample_file", .stack_size = 8, .ver = 50, .ver_max = 66 },
            .{ .name = "AIL_set_3D_position", .stack_size = 16, .ver = 50, .ver_max = 66 },
            .{ .name = "AIL_set_3D_velocity", .stack_size = 20, .ver = 50, .ver_max = 66 },
            .{ .name = "AIL_set_3D_orientation", .stack_size = 28, .ver = 50, .ver_max = 66 },
            // v6+ simplified the distances calls to 3 args (@12); v4/v5 used the
            // wider 5-arg (@20) form (v5 also adds a float_distances @20 pair).
            .{ .name = "AIL_set_3D_sample_distances", .stack_size = 12, .ver = 60, .ver_max = 69 },
            .{ .name = "AIL_set_3D_sample_distances", .stack_size = 20, .ver = 40, .ver_max = 59, .symbol = "AIL_set_3D_sample_distances_v4" },
            .{ .name = "AIL_set_3D_sample_float_distances", .stack_size = 20, .ver = 50, .ver_max = 59, .symbol = "AIL_set_3D_sample_float_distances_v5" },
            .{ .name = "AIL_3D_sample_float_distances", .stack_size = 20, .ver = 50, .ver_max = 59, .symbol = "AIL_3D_sample_float_distances_v5" },
            .{ .name = "AIL_set_listener_3D_position", .stack_size = 16, .ver = 70 },
            .{ .name = "AIL_set_listener_3D_velocity", .stack_size = 20, .ver = 70 },
            .{ .name = "AIL_set_listener_3D_orientation", .stack_size = 28, .ver = 70 },
            .{ .name = "AIL_register_timer", .stack_size = 4 },
            .{ .name = "AIL_set_timer_frequency", .stack_size = 8 },
            .{ .name = "AIL_set_timer_period", .stack_size = 8 },
            .{ .name = "AIL_set_timer_user_data", .stack_size = 8 },
            .{ .name = "AIL_start_timer", .stack_size = 4 },
            .{ .name = "AIL_stop_timer", .stack_size = 4 },
            .{ .name = "AIL_release_timer_handle", .stack_size = 4 },
            .{ .name = "AIL_start_all_timers", .stack_size = 0 },
            .{ .name = "AIL_stop_all_timers", .stack_size = 0 },
            .{ .name = "AIL_quick_startup", .stack_size = 20, .ver = 30, .ver_max = 70 },
            .{ .name = "AIL_quick_shutdown", .stack_size = 0, .ver = 30, .ver_max = 70 },
            .{ .name = "AIL_quick_load", .stack_size = 4, .ver = 30, .ver_max = 70 },
            .{ .name = "AIL_quick_load_mem", .stack_size = 8, .ver = 50, .ver_max = 70 },
            .{ .name = "AIL_quick_copy", .stack_size = 4, .ver = 30, .ver_max = 70 },
            .{ .name = "AIL_quick_unload", .stack_size = 4, .ver = 30, .ver_max = 70 },
            .{ .name = "AIL_quick_play", .stack_size = 8, .ver = 30, .ver_max = 70 },
            .{ .name = "AIL_quick_stop", .stack_size = 4, .ver = 40 },
            .{ .name = "AIL_quick_status", .stack_size = 4, .ver = 30, .ver_max = 70 },
            // Volume args switch S32 (0..127) -> F32 (0.0..1.0) in the Miles-7 API.
            // quick_set_volume took S32 0..127 through 6.1 but switched to F32 in
            // 6.5: disassembly of the debug-log format string is "%ld,%ld" in 6.1d,
            // "%f,%f" in 6.5h, and "%s,%s" (float->string) in 7.0k. So the float
            // variant starts at 6.2, not 7.0.
            .{ .name = "AIL_quick_set_volume", .stack_size = 12, .ver = 30, .ver_max = 61 },
            .{ .name = "AIL_quick_set_volume", .stack_size = 12, .ver = 62, .symbol = "AIL_quick_set_volume_f32" },
            .{ .name = "AIL_quick_set_speed", .stack_size = 8, .ver = 30, .ver_max = 70 },
            .{ .name = "AIL_quick_ms_length", .stack_size = 4, .ver = 50, .ver_max = 70 },
            .{ .name = "AIL_quick_ms_position", .stack_size = 4, .ver = 50, .ver_max = 70 },
            .{ .name = "AIL_quick_set_ms_position", .stack_size = 8, .ver = 50, .ver_max = 70 },
            .{ .name = "AIL_redbook_open", .stack_size = 4, .ver_max = 70 },
            .{ .name = "AIL_redbook_close", .stack_size = 4, .ver_max = 70 },
            .{ .name = "AIL_redbook_play", .stack_size = 12, .ver_max = 70 },
            .{ .name = "AIL_redbook_stop", .stack_size = 4, .ver_max = 70 },
            .{ .name = "AIL_redbook_pause", .stack_size = 4, .ver_max = 70 },
            .{ .name = "AIL_redbook_resume", .stack_size = 4, .ver_max = 70 },
            .{ .name = "AIL_redbook_status", .stack_size = 4, .ver_max = 70 },
            .{ .name = "AIL_redbook_tracks", .stack_size = 4, .ver_max = 70 },
            .{ .name = "AIL_open_ASI_provider", .stack_size = 8, .ver = 40 },
            .{ .name = "AIL_close_ASI_provider", .stack_size = 4, .ver = 40 },
            .{ .name = "AIL_ASI_provider_attribute", .stack_size = 8, .ver = 40 },
            .{ .name = "AIL_compress_ASI", .stack_size = 20, .ver = 50, .ver_max = 70 },
            .{ .name = "AIL_decompress_ASI", .stack_size = 24, .ver = 50 },
            .{ .name = "AIL_mem_alloc_lock", .stack_size = 4, .ver = 30 },
            .{ .name = "AIL_mem_free_lock", .stack_size = 4, .ver = 30 },
            // 3D Sample control
            .{ .name = "AIL_start_3D_sample", .stack_size = 4, .ver = 50, .ver_max = 66 },
            .{ .name = "AIL_stop_3D_sample", .stack_size = 4, .ver = 50, .ver_max = 66 },
            .{ .name = "AIL_resume_3D_sample", .stack_size = 4, .ver = 50, .ver_max = 66 },
            .{ .name = "AIL_end_3D_sample", .stack_size = 4, .ver = 50, .ver_max = 66 },
            .{ .name = "AIL_3D_sample_status", .stack_size = 4, .ver = 50, .ver_max = 66 },
            .{ .name = "AIL_3D_sample_volume", .stack_size = 4, .ver = 50, .ver_max = 66 },
            .{ .name = "AIL_set_3D_sample_volume", .stack_size = 8, .ver = 50, .ver_max = 66 },
            .{ .name = "AIL_3D_sample_loop_count", .stack_size = 4, .ver = 50, .ver_max = 66 },
            .{ .name = "AIL_set_3D_sample_loop_count", .stack_size = 8, .ver = 50, .ver_max = 66 },
            .{ .name = "AIL_3D_sample_playback_rate", .stack_size = 4, .ver = 50, .ver_max = 66 },
            .{ .name = "AIL_set_3D_sample_playback_rate", .stack_size = 8, .ver = 50, .ver_max = 66 },
            .{ .name = "AIL_3D_sample_offset", .stack_size = 4, .ver = 50, .ver_max = 66 },
            .{ .name = "AIL_set_3D_sample_offset", .stack_size = 8, .ver = 50, .ver_max = 66 },
            .{ .name = "AIL_3D_sample_length", .stack_size = 4, .ver = 50, .ver_max = 66 },
            .{ .name = "AIL_3D_sample_ms_position", .stack_size = 12, .ver = 50 },
            .{ .name = "AIL_set_3D_sample_ms_position", .stack_size = 8, .ver = 50 },
            .{ .name = "AIL_register_3D_EOS_callback", .stack_size = 8, .ver = 60, .ver_max = 66 },
            .{ .name = "AIL_active_3D_sample_count", .stack_size = 4, .ver = 50, .ver_max = 66 },
            .{ .name = "AIL_3D_user_data", .stack_size = 8, .ver = 50, .ver_max = 66 },
            .{ .name = "AIL_set_3D_user_data", .stack_size = 12, .ver = 50, .ver_max = 66 },
            .{ .name = "AIL_set_3D_sample_info", .stack_size = 8, .ver = 50, .ver_max = 66 },
            .{ .name = "AIL_set_3D_sample_loop_block", .stack_size = 12, .ver = 50, .ver_max = 66 },
            .{ .name = "AIL_set_3D_sample_cone", .stack_size = 16, .ver = 60, .ver_max = 66 },
            .{ .name = "AIL_3D_sample_cone", .stack_size = 16, .ver = 60, .ver_max = 66 },
            .{ .name = "AIL_set_3D_sample_effects_level", .stack_size = 8, .ver = 60, .ver_max = 66 },
            .{ .name = "AIL_3D_sample_effects_level", .stack_size = 4, .ver = 60, .ver_max = 66 },
            .{ .name = "AIL_set_3D_sample_obstruction", .stack_size = 8, .ver = 60, .ver_max = 66 },
            .{ .name = "AIL_3D_sample_obstruction", .stack_size = 4, .ver = 60, .ver_max = 66 },
            .{ .name = "AIL_set_3D_sample_occlusion", .stack_size = 8, .ver = 60, .ver_max = 66 },
            .{ .name = "AIL_3D_sample_occlusion", .stack_size = 4, .ver = 60, .ver_max = 66 },
            .{ .name = "AIL_set_3D_sample_preference", .stack_size = 12, .ver = 50, .ver_max = 66 },
            .{ .name = "AIL_3D_sample_attribute", .stack_size = 12, .ver = 50, .ver_max = 66 },
            .{ .name = "AIL_auto_update_3D_position", .stack_size = 8, .ver = 61, .ver_max = 66 },
            .{ .name = "AIL_update_3D_position", .stack_size = 8, .ver = 61, .ver_max = 66 },
            .{ .name = "AIL_set_3D_velocity_vector", .stack_size = 16, .ver = 50, .ver_max = 66 },
            // 3D Environment
            .{ .name = "AIL_set_3D_distance_factor", .stack_size = 8, .ver = 61 },
            .{ .name = "AIL_3D_distance_factor", .stack_size = 4, .ver = 61 },
            .{ .name = "AIL_set_3D_doppler_factor", .stack_size = 8, .ver = 61 },
            .{ .name = "AIL_3D_doppler_factor", .stack_size = 4, .ver = 61 },
            .{ .name = "AIL_set_3D_rolloff_factor", .stack_size = 8, .ver = 61 },
            .{ .name = "AIL_3D_rolloff_factor", .stack_size = 4, .ver = 61 },
            .{ .name = "AIL_set_3D_room_type", .stack_size = 8, .ver = 60, .ver_max = 66 },
            .{ .name = "AIL_3D_room_type", .stack_size = 4, .ver = 60, .ver_max = 66 },
            .{ .name = "AIL_set_3D_speaker_type", .stack_size = 8, .ver = 60, .ver_max = 66 },
            .{ .name = "AIL_3D_speaker_type", .stack_size = 4, .ver = 60, .ver_max = 66 },
            // 3D Provider/Listener/Object
            .{ .name = "AIL_open_3D_provider", .stack_size = 4, .ver = 50, .ver_max = 66 },
            .{ .name = "AIL_close_3D_provider", .stack_size = 4, .ver = 50, .ver_max = 66 },
            .{ .name = "AIL_open_3D_listener", .stack_size = 4, .ver = 50, .ver_max = 66 },
            .{ .name = "AIL_close_3D_listener", .stack_size = 4, .ver = 50, .ver_max = 66 },
            .{ .name = "AIL_open_3D_object", .stack_size = 4, .ver = 50, .ver_max = 66 },
            .{ .name = "AIL_close_3D_object", .stack_size = 4, .ver = 50, .ver_max = 66 },
            .{ .name = "AIL_3D_provider_attribute", .stack_size = 12, .ver = 50, .ver_max = 66 },
            .{ .name = "AIL_set_3D_provider_preference", .stack_size = 12, .ver = 50, .ver_max = 66 },
            .{ .name = "AIL_enumerate_3D_provider_attributes", .stack_size = 12, .ver = 50, .ver_max = 66 },
            .{ .name = "AIL_enumerate_3D_sample_attributes", .stack_size = 12, .ver = 50, .ver_max = 66 },
            .{ .name = "AIL_3D_orientation", .stack_size = 28, .ver = 50, .ver_max = 66 },
            .{ .name = "AIL_3D_position", .stack_size = 16, .ver = 50, .ver_max = 66 },
            .{ .name = "AIL_3D_velocity", .stack_size = 16, .ver = 50, .ver_max = 66 },
            .{ .name = "AIL_3D_update_position", .stack_size = 8, .ver = 50, .ver_max = 60 },
            .{ .name = "AIL_3D_auto_update_position", .stack_size = 8, .ver = 50, .ver_max = 60 },
            .{ .name = "AIL_get_DirectSound3D_info", .stack_size = 16, .ver_max = 39 },
            .{ .name = "AIL_set_direct_buffer_control", .stack_size = 8, .ver_max = 50 },
            .{ .name = "AIL_start_sample_at", .stack_size = 8, .ver_max = 39 },
            .{ .name = "AIL_open_stream_ex", .stack_size = 16, .ver_max = 39 },
            .{ .name = "AIL_3D_sample_distances", .stack_size = 12, .ver = 60, .ver_max = 69 },
            .{ .name = "AIL_3D_sample_distances", .stack_size = 20, .ver = 40, .ver_max = 59, .symbol = "AIL_3D_sample_distances_v4" },
            // Sequence extras
            .{ .name = "AIL_sequence_ms_position", .stack_size = 12, .ver = 50, .ver_max = 70 },
            .{ .name = "AIL_set_sequence_ms_position", .stack_size = 8, .ver = 50, .ver_max = 70 },
            .{ .name = "AIL_sequence_loop_count", .stack_size = 4, .ver_max = 70 },
            .{ .name = "AIL_sequence_volume", .stack_size = 4, .ver_max = 70 },
            .{ .name = "AIL_sequence_tempo", .stack_size = 4, .ver_max = 70 },
            .{ .name = "AIL_set_sequence_tempo", .stack_size = 12, .ver_max = 70 },
            .{ .name = "AIL_active_sequence_count", .stack_size = 4, .ver_max = 70 },
            .{ .name = "AIL_sequence_position", .stack_size = 12, .ver_max = 70 },
            .{ .name = "AIL_sequence_user_data", .stack_size = 8, .ver_max = 70 },
            .{ .name = "AIL_set_sequence_user_data", .stack_size = 12, .ver_max = 70 },
            .{ .name = "AIL_end_sequence", .stack_size = 4, .ver_max = 70 },
            .{ .name = "AIL_channel_notes", .stack_size = 8, .ver_max = 70 },
            .{ .name = "AIL_true_sequence_channel", .stack_size = 8, .ver_max = 70 },
            .{ .name = "AIL_map_sequence_channel", .stack_size = 12, .ver_max = 70 },
            .{ .name = "AIL_controller_value", .stack_size = 12, .ver_max = 70 },
            .{ .name = "AIL_send_channel_voice_message", .stack_size = 20, .ver_max = 70 },
            .{ .name = "AIL_send_sysex_message", .stack_size = 8, .ver_max = 70 },
            .{ .name = "AIL_lock_channel", .stack_size = 4, .ver_max = 70 },
            .{ .name = "AIL_release_channel", .stack_size = 8, .ver_max = 70 },
            .{ .name = "AIL_register_beat_callback", .stack_size = 8, .ver_max = 70 },
            .{ .name = "AIL_register_event_callback", .stack_size = 8, .ver_max = 70 },
            .{ .name = "AIL_register_prefix_callback", .stack_size = 8, .ver_max = 70 },
            .{ .name = "AIL_register_trigger_callback", .stack_size = 8, .ver_max = 70 },
            .{ .name = "AIL_register_sequence_callback", .stack_size = 8, .ver_max = 70 },
            .{ .name = "AIL_register_timbre_callback", .stack_size = 8, .ver_max = 70 },
            .{ .name = "AIL_register_ICA_array", .stack_size = 8, .ver_max = 70 },
            .{ .name = "AIL_XMIDI_master_volume", .stack_size = 4, .ver_max = 70 },
            .{ .name = "AIL_set_XMIDI_master_volume", .stack_size = 8, .ver_max = 70 },
            .{ .name = "AIL_midiOutClose", .stack_size = 4, .ver_max = 70 },
            .{ .name = "AIL_midiOutOpen", .stack_size = 12, .ver_max = 70 },
            .{ .name = "AIL_MIDI_handle_release", .stack_size = 4, .ver_max = 70 },
            .{ .name = "AIL_MIDI_handle_reacquire", .stack_size = 4, .ver_max = 70 },
            .{ .name = "AIL_MIDI_to_XMI", .stack_size = 20, .ver = 50, .ver_max = 70 },
            // Sample extras
            .{ .name = "AIL_sample_user_data", .stack_size = 8 },
            .{ .name = "AIL_set_sample_user_data", .stack_size = 12 },
            .{ .name = "AIL_sample_reverb", .stack_size = 16, .ver = 60, .ver_max = 61 },
            .{ .name = "AIL_set_sample_reverb", .stack_size = 16, .ver = 60, .ver_max = 61 },
            .{ .name = "AIL_set_sample_loop_block", .stack_size = 12 },
            .{ .name = "AIL_set_sample_adpcm_block_size", .stack_size = 8, .ver = 50 },
            .{ .name = "AIL_sample_granularity", .stack_size = 4, .ver = 50 },
            .{ .name = "AIL_minimum_sample_buffer_size", .stack_size = 12 },
            .{ .name = "AIL_allocate_file_sample", .stack_size = 12, .ver_max = 66 },
            .{ .name = "AIL_load_sample_buffer", .stack_size = 16 },
            .{ .name = "AIL_sample_buffer_ready", .stack_size = 4, .ver_max = 70 },
            .{ .name = "AIL_sample_buffer_info", .stack_size = 20, .ver_max = 70, .symbol = "AIL_sample_buffer_info_old" },
            .{ .name = "AIL_sample_buffer_info", .stack_size = 24, .ver = 80 },
            .{ .name = "AIL_register_EOB_callback", .stack_size = 8 },
            .{ .name = "AIL_register_SOB_callback", .stack_size = 8 },
            .{ .name = "AIL_set_sample_processor", .stack_size = 12, .ver = 50 },
            // Stream extras
            .{ .name = "AIL_stream_position", .stack_size = 4 },
            .{ .name = "AIL_set_stream_position", .stack_size = 8 },
            .{ .name = "AIL_stream_user_data", .stack_size = 8 },
            .{ .name = "AIL_set_stream_user_data", .stack_size = 12 },
            .{ .name = "AIL_stream_reverb", .stack_size = 16, .ver = 60, .ver_max = 61 },
            .{ .name = "AIL_set_stream_reverb", .stack_size = 16, .ver = 60, .ver_max = 61 },
            .{ .name = "AIL_stream_info", .stack_size = 20 },
            .{ .name = "AIL_set_stream_loop_block", .stack_size = 12, .ver = 60 },
            .{ .name = "AIL_service_stream", .stack_size = 8 },
            .{ .name = "AIL_register_EOF_callback", .stack_size = 8, .ver_max = 66 },
            .{ .name = "AIL_set_stream_processor", .stack_size = 12, .ver = 61, .ver_max = 66 },
            .{ .name = "AIL_filter_stream_attribute", .stack_size = 12, .ver = 60, .ver_max = 66 },
            .{ .name = "AIL_set_filter_stream_preference", .stack_size = 12, .ver = 60, .ver_max = 66 },
            // Filter extras
            .{ .name = "AIL_enumerate_filter_attributes", .stack_size = 12, .ver = 60, .ver_max = 66 },
            .{ .name = "AIL_enumerate_filter_sample_attributes", .stack_size = 12, .ver = 60, .ver_max = 66 },
            .{ .name = "AIL_filter_sample_attribute", .stack_size = 12, .ver = 60, .ver_max = 66 },
            .{ .name = "AIL_set_filter_sample_preference", .stack_size = 12, .ver = 60, .ver_max = 66 },
            .{ .name = "AIL_set_filter_DLS_preference", .stack_size = 12, .ver = 60, .ver_max = 66 },
            .{ .name = "AIL_set_filter_preference", .stack_size = 12, .ver = 60, .ver_max = 66 },
            .{ .name = "AIL_filter_DLS_attribute", .stack_size = 12, .ver = 60, .ver_max = 66 },
            .{ .name = "AIL_filter_DLS_with_XMI", .stack_size = 24, .ver = 50, .ver_max = 70 },
            // Quick API extras
            .{ .name = "AIL_quick_halt", .stack_size = 4, .ver = 30, .ver_max = 70 },
            .{ .name = "AIL_quick_set_reverb", .stack_size = 16, .ver = 60, .ver_max = 61 },
            .{ .name = "AIL_quick_load_and_play", .stack_size = 12, .ver = 30, .ver_max = 70 },
            .{ .name = "AIL_quick_type", .stack_size = 4, .ver = 50, .ver_max = 70 },
            .{ .name = "AIL_quick_handles", .stack_size = 8, .ver = 30, .ver_max = 39, .symbol = "AIL_quick_handles_v3" },
            .{ .name = "AIL_quick_handles", .stack_size = 12, .ver = 40 },
            // DLS extras
            .{ .name = "AIL_DLS_load_memory", .stack_size = 12, .ver = 50, .ver_max = 70 },
            .{ .name = "AIL_DLS_unload", .stack_size = 8, .ver = 50, .ver_max = 70 },
            .{ .name = "AIL_DLS_compact", .stack_size = 4, .ver = 50, .ver_max = 70 },
            .{ .name = "AIL_DLS_get_info", .stack_size = 12, .ver = 50, .ver_max = 70 },
            .{ .name = "AIL_DLS_get_reverb", .stack_size = 16, .ver = 60, .ver_max = 61 },
            .{ .name = "AIL_DLS_set_reverb", .stack_size = 16, .ver = 60, .ver_max = 61 },
            .{ .name = "AIL_DLS_open", .stack_size = 28, .ver = 50, .ver_max = 70 },
            .{ .name = "AIL_DLS_close", .stack_size = 8, .ver = 50, .ver_max = 70 },
            // Redbook extras
            .{ .name = "AIL_redbook_eject", .stack_size = 4, .ver_max = 70 },
            .{ .name = "AIL_redbook_retract", .stack_size = 4, .ver_max = 70 },
            .{ .name = "AIL_redbook_id", .stack_size = 4, .ver_max = 70 },
            .{ .name = "AIL_redbook_open_drive", .stack_size = 4, .ver = 50, .ver_max = 70 },
            .{ .name = "AIL_redbook_position", .stack_size = 4, .ver_max = 70 },
            .{ .name = "AIL_redbook_track", .stack_size = 4, .ver_max = 70 },
            .{ .name = "AIL_redbook_track_info", .stack_size = 16, .ver_max = 70 },
            .{ .name = "AIL_redbook_set_volume", .stack_size = 8, .ver_max = 61 },
            .{ .name = "AIL_redbook_volume", .stack_size = 4, .ver_max = 61 },
            // RIB extras
            .{ .name = "RIB_error", .stack_size = 0, .ver = 40, .cdecl = true, .ver_max = 79 },
            .{ .name = "RIB_error", .stack_size = 0, .ver = 80, .symbol = "RIB_error_std" },
            .{ .name = "RIB_find_file_provider", .stack_size = 12, .ver = 40, .cdecl = true, .ver_max = 79 },
            .{ .name = "RIB_find_file_provider", .stack_size = 12, .ver = 80, .symbol = "RIB_find_file_provider_std" },
            .{ .name = "RIB_load_provider_library", .stack_size = 4, .ver = 40, .cdecl = true, .ver_max = 79 },
            .{ .name = "RIB_load_provider_library", .stack_size = 4, .ver = 80, .symbol = "RIB_load_provider_library_std" },
            .{ .name = "RIB_free_provider_library", .stack_size = 4, .ver = 40, .cdecl = true, .ver_max = 79 },
            .{ .name = "RIB_free_provider_library", .stack_size = 4, .ver = 80, .symbol = "RIB_free_provider_library_std" },
            .{ .name = "RIB_request_interface_entry", .stack_size = 20, .ver = 40, .cdecl = true, .ver_max = 79 },
            .{ .name = "RIB_request_interface_entry", .stack_size = 20, .ver = 80, .symbol = "RIB_request_interface_entry_std" },
            .{ .name = "RIB_enumerate_interface", .stack_size = 20, .ver = 40, .cdecl = true, .ver_max = 79 },
            .{ .name = "RIB_enumerate_interface", .stack_size = 20, .ver = 80, .symbol = "RIB_enumerate_interface_std" },
            .{ .name = "RIB_type_string", .stack_size = 8, .ver = 40, .cdecl = true, .ver_max = 79 },
            .{ .name = "RIB_type_string", .stack_size = 8, .ver = 80, .symbol = "RIB_type_string_std" },
            // v9-only: v7/v8 export MIX_RIB_MAIN@8 (a different ASI entry arity);
            // v4-v6 and v7/v8 do not export MSS_alloc_info/MSS_free_info at all.
            .{ .name = "MIX_RIB_MAIN", .stack_size = 20, .ver = 90 },
            .{ .name = "MIX_RIB_MAIN", .stack_size = 8, .ver = 65, .ver_max = 80, .symbol = "MIX_RIB_MAIN_v7" },
            // Intermittent export: present in 6.x and v8 (8.0j), absent from v5,
            // v7, and v9 — two separate version ranges.
            .{ .name = "MSSDisableThreadLibraryCalls", .stack_size = 4, .ver = 80, .ver_max = 89 },
            .{ .name = "MSS_alloc_info", .stack_size = 16, .ver = 90 },
            .{ .name = "MSS_free_info", .stack_size = 16, .ver = 90 },
            .{ .name = "RIB_provider_system_data", .stack_size = 8, .ver = 50 },
            .{ .name = "RIB_provider_user_data", .stack_size = 8, .ver = 50 },
            .{ .name = "RIB_set_provider_system_data", .stack_size = 12, .ver = 50 },
            .{ .name = "RIB_set_provider_user_data", .stack_size = 12, .ver = 50 },
            .{ .name = "RIB_find_file_dec_provider", .stack_size = 20, .ver = 61 },
            .{ .name = "RIB_find_provider", .stack_size = 12, .ver = 60 },
            // Digital driver extras
            .{ .name = "AIL_primary_digital_driver", .stack_size = 4, .ver = 60 },
            .{ .name = "AIL_digital_CPU_percent", .stack_size = 4, .ver = 50 },
            .{ .name = "AIL_digital_latency", .stack_size = 4, .ver = 60 },
            .{ .name = "AIL_digital_configuration", .stack_size = 16 },
            .{ .name = "AIL_get_DirectSound_info", .stack_size = 12, .ver_max = 70 },
            .{ .name = "AIL_set_DirectSound_HWND", .stack_size = 8, .ver = 50, .ver_max = 70 },
            .{ .name = "AIL_set_digital_driver_processor", .stack_size = 12, .ver = 50 },
            .{ .name = "AIL_process_digital_audio", .stack_size = 24, .ver = 50 },
            .{ .name = "AIL_size_processed_digital_audio", .stack_size = 16, .ver = 50 },
            // Utility
            .{ .name = "AIL_ms_count", .stack_size = 0 },
            .{ .name = "AIL_us_count", .stack_size = 0, .ver = 50 },
            .{ .name = "AIL_delay", .stack_size = 4, .ver_max = 80 },
            .{ .name = "AIL_lock", .stack_size = 0, .ver_max = 80 },
            .{ .name = "AIL_unlock", .stack_size = 0, .ver_max = 80 },
            .{ .name = "AIL_lock_mutex", .stack_size = 0, .ver = 60 },
            .{ .name = "AIL_unlock_mutex", .stack_size = 0, .ver = 60 },
            .{ .name = "AIL_background", .stack_size = 0 },
            .{ .name = "AIL_MMX_available", .stack_size = 0, .ver = 50 },
            .{ .name = "AIL_HWND", .stack_size = 0, .ver = 50, .ver_max = 70 },
            .{ .name = "AIL_set_error", .stack_size = 4 },
            .{ .name = "AIL_get_timer_highest_delay", .stack_size = 0, .ver = 60 },
            .{ .name = "AIL_set_timer_divisor", .stack_size = 8, .ver_max = 80 },
            .{ .name = "AIL_set_timer_user", .stack_size = 8 },
            .{ .name = "AIL_release_all_timers", .stack_size = 0 },
            .{ .name = "AIL_file_error", .stack_size = 0 },
            .{ .name = "AIL_file_read", .stack_size = 8 },
            .{ .name = "AIL_file_size", .stack_size = 4 },
            .{ .name = "AIL_file_type", .stack_size = 8, .ver = 50 },
            .{ .name = "AIL_file_write", .stack_size = 12 },
            .{ .name = "AIL_WAV_info", .stack_size = 8, .ver = 50 },
            .{ .name = "AIL_WAV_file_write", .stack_size = 20, .ver = 50 },
            .{ .name = "AIL_mem_use_malloc", .stack_size = 4, .ver = 61 },
            .{ .name = "AIL_mem_use_free", .stack_size = 4, .ver = 61 },
            .{ .name = "AIL_set_mem_callbacks", .stack_size = 8, .ver = 40 },
            .{ .name = "AIL_compress_ADPCM", .stack_size = 12, .ver = 50, .ver_max = 70 },
            .{ .name = "AIL_decompress_ADPCM", .stack_size = 12, .ver = 50 },
            // v4/v5 used AIL_input_open@12 / AIL_input_close@4; v6 renamed them to
            // the 1-arg AIL_open_input@4 / AIL_close_input@4.
            .{ .name = "AIL_input_open", .stack_size = 12, .ver = 40, .ver_max = 59 },
            .{ .name = "AIL_input_close", .stack_size = 4, .ver = 40, .ver_max = 59, .symbol = "AIL_close_input" },
            .{ .name = "AIL_open_input", .stack_size = 4, .ver = 60 },
            .{ .name = "AIL_close_input", .stack_size = 4, .ver = 60 },
            .{ .name = "AIL_set_input_state", .stack_size = 8, .ver = 60 },
            // 6.0-only spelling: 6.0a-6.0m export AIL_input_info@4; from 6.1 the
            // same shape ships as get_input_info (below). Never in 7.x+.
            .{ .name = "AIL_input_info", .stack_size = 4, .ver = 60, .ver_max = 60 },
            .{ .name = "AIL_get_input_info", .stack_size = 4, .ver = 61, .symbol = "AIL_input_info" },
            .{ .name = "AIL_set_file_callbacks", .stack_size = 16, .ver = 61 },
            .{ .name = "AIL_set_file_async_callbacks", .stack_size = 20, .ver = 61, .ver_max = 80 },
            .{ .name = "AIL_set_DLS_processor", .stack_size = 12, .ver = 61, .ver_max = 66 },
            .{ .name = "AIL_create_wave_synthesizer", .stack_size = 16, .ver_max = 70 },
            .{ .name = "AIL_destroy_wave_synthesizer", .stack_size = 4, .ver_max = 70 },
            .{ .name = "AIL_waveOutClose", .stack_size = 4, .ver_max = 66 },
            // EOB ASI reset: v7 @8 (HSAMPLE, buff_num); v8+ added new_stream_position.
            // Arity oscillates across point releases: 6.0 @8, 6.1 @12, 7.0b-d
            // @8, 7.0h+/8.x @12. We target the dominant families — the 6.0
            // mainline (@8) for v6, and 7.0h+ (@12) for v7+.
            .{ .name = "AIL_request_EOB_ASI_reset", .stack_size = 8, .ver = 60, .ver_max = 69, .symbol = "AIL_request_EOB_ASI_reset_v7" },
            .{ .name = "AIL_request_EOB_ASI_reset", .stack_size = 12, .ver = 70 },
            // DLS utilities
            .{ .name = "AIL_compress_DLS", .stack_size = 20, .ver = 50, .ver_max = 70 },
            .{ .name = "AIL_extract_DLS", .stack_size = 28, .ver = 50, .ver_max = 70 },
            .{ .name = "AIL_find_DLS", .stack_size = 24, .ver = 50, .ver_max = 70 },
            .{ .name = "AIL_list_DLS", .stack_size = 20, .ver = 50, .ver_max = 70 },
            .{ .name = "AIL_list_MIDI", .stack_size = 20, .ver = 50, .ver_max = 70 },
            .{ .name = "AIL_merge_DLS_with_XMI", .stack_size = 16, .ver = 50, .ver_max = 70 },
            // Legacy DLS* functions (no AIL_ prefix)
            .{ .name = "DLSClose", .stack_size = 8, .ver = 50, .cdecl = true, .ver_max = 70 },
            .{ .name = "DLSCompactMemory", .stack_size = 4, .ver = 50, .cdecl = true, .ver_max = 70 },
            .{ .name = "DLSGetInfo", .stack_size = 12, .ver = 50, .cdecl = true, .ver_max = 70 },
            .{ .name = "DLSLoadFile", .stack_size = 12, .ver = 50, .cdecl = true, .ver_max = 70 },
            .{ .name = "DLSLoadMemFile", .stack_size = 12, .ver = 50, .cdecl = true, .ver_max = 70 },
            .{ .name = "DLSMSSGetCPU", .stack_size = 4, .ver = 50, .ver_max = 70 },
            .{ .name = "DLSMSSOpen", .stack_size = 28, .ver = 50, .cdecl = true, .ver_max = 70 },
            .{ .name = "DLSSetAttribute", .stack_size = 12, .ver = 50, .cdecl = true, .ver_max = 70 },
            .{ .name = "DLSUnloadAll", .stack_size = 4, .ver = 50, .cdecl = true, .ver_max = 70 },
            .{ .name = "DLSUnloadFile", .stack_size = 8, .ver = 50, .cdecl = true, .ver_max = 70 },
            // DLL entry point
            .{ .name = "DllMain", .stack_size = 12, .ver_max = 70 },
            .{ .name = "AIL_set_sample_3D_position", .stack_size = 16, .ver = 70 },
            .{ .name = "AIL_set_sample_3D_velocity", .stack_size = 20, .ver = 70 },
            .{ .name = "AIL_set_sample_3D_velocity_vector", .stack_size = 16, .ver = 70 },
            .{ .name = "AIL_set_sample_3D_orientation", .stack_size = 28, .ver = 70 },
            .{ .name = "AIL_set_sample_3D_cone", .stack_size = 16, .ver = 70 },
            .{ .name = "AIL_set_sample_3D_distances", .stack_size = 16, .ver = 70 },
            .{ .name = "AIL_update_sample_3D_position", .stack_size = 8, .ver = 70 },
            .{ .name = "AIL_sample_3D_position", .stack_size = 16, .ver = 70 },
            .{ .name = "AIL_sample_3D_velocity", .stack_size = 16, .ver = 70 },
            .{ .name = "AIL_sample_3D_orientation", .stack_size = 28, .ver = 70 },
            .{ .name = "AIL_sample_3D_cone", .stack_size = 16, .ver = 70 },
            .{ .name = "AIL_sample_3D_distances", .stack_size = 16, .ver = 70 },
            .{ .name = "AIL_set_sample_volume_levels", .stack_size = 12, .ver = 65 },
            .{ .name = "AIL_sample_volume_levels", .stack_size = 12, .ver = 65 },
            .{ .name = "AIL_sample_volume_pan", .stack_size = 12, .ver = 65 },
            // low-pass cutoff first appears in 6.5 as the narrow no-channel
            // form (set @8 / get @4), carried through 7.x. v8 widened it with a
            // channel parameter (set @12 / get @8), kept through v9. 6.0/6.1
            // never exported it, so it is gated to 65+.
            .{ .name = "AIL_set_sample_low_pass_cut_off", .stack_size = 12, .ver = 80 },
            .{ .name = "AIL_set_sample_low_pass_cut_off", .stack_size = 8, .ver = 65, .ver_max = 70, .symbol = "AIL_set_sample_low_pass_cut_off_v7" },
            .{ .name = "AIL_sample_low_pass_cut_off", .stack_size = 8, .ver = 80 },
            .{ .name = "AIL_sample_low_pass_cut_off", .stack_size = 4, .ver = 65, .ver_max = 70, .symbol = "AIL_sample_low_pass_cut_off_v7" },
            .{ .name = "AIL_set_sample_reverb_levels", .stack_size = 12, .ver = 65 },
            .{ .name = "AIL_sample_reverb_levels", .stack_size = 12, .ver = 65 },
            .{ .name = "AIL_set_sample_info", .stack_size = 8, .ver = 70 },
            .{ .name = "AIL_set_sample_obstruction", .stack_size = 8, .ver = 70 },
            .{ .name = "AIL_sample_obstruction", .stack_size = 4, .ver = 70 },
            .{ .name = "AIL_set_sample_occlusion", .stack_size = 8, .ver = 70 },
            .{ .name = "AIL_sample_occlusion", .stack_size = 4, .ver = 70 },
            .{ .name = "AIL_set_sample_exclusion", .stack_size = 8, .ver = 70 },
            .{ .name = "AIL_sample_exclusion", .stack_size = 4, .ver = 70 },
            .{ .name = "AIL_listener_3D_position", .stack_size = 16, .ver = 70 },
            .{ .name = "AIL_listener_3D_velocity", .stack_size = 16, .ver = 70 },
            .{ .name = "AIL_listener_3D_orientation", .stack_size = 28, .ver = 70 },
            .{ .name = "AIL_set_listener_3D_velocity_vector", .stack_size = 16, .ver = 70 },
            .{ .name = "AIL_update_listener_3D_position", .stack_size = 8, .ver = 70 },
            .{ .name = "AIL_digital_master_volume_level", .stack_size = 4, .ver = 65 },
            .{ .name = "AIL_set_digital_master_volume_level", .stack_size = 8, .ver = 65 },
            .{ .name = "AIL_set_digital_master_reverb", .stack_size = 20, .ver = 90 },
            .{ .name = "AIL_set_digital_master_reverb", .stack_size = 16, .ver = 65, .ver_max = 80, .symbol = "AIL_set_digital_master_reverb_v7" },
            .{ .name = "AIL_digital_master_reverb", .stack_size = 20, .ver = 90 },
            .{ .name = "AIL_digital_master_reverb", .stack_size = 16, .ver = 65, .ver_max = 80, .symbol = "AIL_digital_master_reverb_v7" },
            .{ .name = "AIL_set_digital_master_reverb_levels", .stack_size = 16, .ver = 90 },
            .{ .name = "AIL_set_digital_master_reverb_levels", .stack_size = 12, .ver = 65, .ver_max = 80, .symbol = "AIL_set_digital_master_reverb_levels_v7" },
            .{ .name = "AIL_digital_master_reverb_levels", .stack_size = 16, .ver = 90 },
            .{ .name = "AIL_digital_master_reverb_levels", .stack_size = 12, .ver = 65, .ver_max = 80, .symbol = "AIL_digital_master_reverb_levels_v7" },
            .{ .name = "AIL_set_room_type", .stack_size = 12, .ver = 90 },
            .{ .name = "AIL_set_room_type", .stack_size = 8, .ver = 70, .ver_max = 80, .symbol = "AIL_set_room_type_v7" },
            .{ .name = "AIL_room_type", .stack_size = 8, .ver = 90 },
            .{ .name = "AIL_room_type", .stack_size = 4, .ver = 70, .ver_max = 80, .symbol = "AIL_room_type_v7" },
            .{ .name = "AIL_redbook_set_volume_level", .stack_size = 8, .ver = 65, .ver_max = 70 },
            .{ .name = "AIL_redbook_volume_level", .stack_size = 4, .ver = 65, .ver_max = 70 },
            // 6.5-7.x take the narrow (HAUDIO, F32) @8; v8+ widened it to
            // (HAUDIO, S32 channel, F32) @12.
            .{ .name = "AIL_quick_set_low_pass_cut_off", .stack_size = 8, .ver = 65, .ver_max = 70, .symbol = "AIL_quick_set_low_pass_cut_off_v7" },
            .{ .name = "AIL_quick_set_low_pass_cut_off", .stack_size = 12, .ver = 80 },
            .{ .name = "AIL_quick_set_reverb_levels", .stack_size = 12, .ver = 65, .ver_max = 70 },
            // 6.5/6.6-only APIs (added in 6.5, dropped in 7.x): per-stream
            // volume/pan/reverb/low-pass, H3DSAMPLE exclusion, DLS reverb-level
            // pair, and the 6.x master room-type spelling.
            .{ .name = "AIL_set_stream_volume_levels", .stack_size = 12, .ver = 65, .ver_max = 66 },
            .{ .name = "AIL_stream_volume_levels", .stack_size = 12, .ver = 65, .ver_max = 66 },
            .{ .name = "AIL_stream_volume_pan", .stack_size = 12, .ver = 65, .ver_max = 66 },
            .{ .name = "AIL_set_stream_reverb_levels", .stack_size = 12, .ver = 65, .ver_max = 66 },
            .{ .name = "AIL_stream_reverb_levels", .stack_size = 12, .ver = 65, .ver_max = 66 },
            .{ .name = "AIL_set_stream_low_pass_cut_off", .stack_size = 8, .ver = 65, .ver_max = 66 },
            .{ .name = "AIL_stream_low_pass_cut_off", .stack_size = 4, .ver = 65, .ver_max = 66 },
            // First appeared in the 6.1d patch (absent in 6.1a/6.1c), present through 6.6.
            .{ .name = "AIL_set_3D_sample_exclusion", .stack_size = 8, .ver = 61, .ver_max = 66 },
            .{ .name = "AIL_3D_sample_exclusion", .stack_size = 4, .ver = 61, .ver_max = 66 },
            .{ .name = "AIL_DLS_set_reverb_levels", .stack_size = 12, .ver = 65, .ver_max = 66 },
            .{ .name = "AIL_DLS_get_reverb_levels", .stack_size = 12, .ver = 65, .ver_max = 66 },
            .{ .name = "AIL_set_digital_master_room_type", .stack_size = 8, .ver = 65, .ver_max = 66 },
            .{ .name = "AIL_stream_sample_handle", .stack_size = 4, .ver = 70 },
            .{ .name = "AIL_DLS_sample_handle", .stack_size = 4, .ver = 70, .ver_max = 70 },
            .{ .name = "AIL_find_filter", .stack_size = 8, .ver = 70 },
            .{ .name = "AIL_background_CPU_percent", .stack_size = 0, .ver = 70 },
            .{ .name = "AIL_sample_processor", .stack_size = 8, .ver = 70 },
            .{ .name = "AIL_digital_driver_processor", .stack_size = 8, .ver = 70 },
            // DSP stage attributes were a v7-only API (@16, with a stage index).
            .{ .name = "AIL_sample_stage_attribute", .stack_size = 16, .ver = 70, .ver_max = 70, .symbol = "AIL_sample_stage_attribute_v7" },
            .{ .name = "AIL_set_sample_stage_preference", .stack_size = 16, .ver = 70, .ver_max = 70, .symbol = "AIL_set_sample_stage_preference_v7" },
            .{ .name = "AIL_enumerate_sample_stage_attributes", .stack_size = 16, .ver = 70, .ver_max = 70, .symbol = "AIL_enumerate_sample_stage_attributes_v7" },
            // channel levels: v7 @8/@12 lacked the src/dst matrices v8 added (@20).
            .{ .name = "AIL_sample_channel_levels", .stack_size = 20, .ver = 80 },
            .{ .name = "AIL_sample_channel_levels", .stack_size = 8, .ver = 70, .ver_max = 70, .symbol = "AIL_sample_channel_levels_v7" },
            .{ .name = "AIL_set_sample_channel_levels", .stack_size = 20, .ver = 80 },
            .{ .name = "AIL_set_sample_channel_levels", .stack_size = 12, .ver = 70, .ver_max = 70, .symbol = "AIL_set_sample_channel_levels_v7" },
            .{ .name = "AIL_listener_relative_receiver_array", .stack_size = 8, .ver = 70 },
            .{ .name = "AIL_set_listener_relative_receiver_array", .stack_size = 12, .ver = 70 },
            .{ .name = "AIL_speaker_configuration", .stack_size = 20, .ver = 70 },
            .{ .name = "AIL_set_speaker_configuration", .stack_size = 16, .ver = 70 },
            .{ .name = "AIL_speaker_reverb_levels", .stack_size = 16, .ver = 70 },
            // speaker reverb levels: v7 @16 lacked the per-speaker index array (v8 @20).
            .{ .name = "AIL_set_speaker_reverb_levels", .stack_size = 20, .ver = 80 },
            .{ .name = "AIL_set_speaker_reverb_levels", .stack_size = 16, .ver = 70, .ver_max = 70, .symbol = "AIL_set_speaker_reverb_levels_v7" },
            .{ .name = "AIL_calculate_3D_channel_levels", .stack_size = 56, .ver = 70, .ver_max = 70, .symbol = "AIL_calculate_3D_channel_levels_v7" },
            .{ .name = "AIL_calculate_3D_channel_levels", .stack_size = 68, .ver = 80 },
            .{ .name = "AIL_digital_output_filter", .stack_size = 4, .ver = 70 },
            .{ .name = "AIL_output_filter_driver_attribute", .stack_size = 12, .ver = 70, .ver_max = 79 },
            .{ .name = "AIL_set_output_filter_driver_preference", .stack_size = 12, .ver = 70, .ver_max = 79 },
            .{ .name = "AIL_enumerate_output_filter_driver_attributes", .stack_size = 12, .ver = 70, .ver_max = 79 },
            .{ .name = "AIL_enumerate_output_filter_sample_attributes", .stack_size = 12, .ver = 70, .ver_max = 79 },
            .{ .name = "AIL_inspect_MP3", .stack_size = 12, .ver = 70, .ver_max = 70 },
            .{ .name = "AIL_enumerate_MP3_frames", .stack_size = 4, .ver = 70, .ver_max = 70 },
            .{ .name = "RIB_load_static_provider_library", .stack_size = 8, .ver = 65 },
            .{ .name = "AIL_WAV_marker_by_index", .stack_size = 12, .ver = 80 },
            .{ .name = "AIL_WAV_marker_by_name", .stack_size = 8, .ver = 80 },
            .{ .name = "AIL_WAV_marker_count", .stack_size = 4, .ver = 80 },
            // v8 form @8 (2-arg); v9 adds a trailing S32 (@12).
            .{ .name = "AIL_add_apply_environment_event_step", .stack_size = 12, .ver = 90 },
            .{ .name = "AIL_add_apply_environment_event_step", .stack_size = 8, .ver = 80, .ver_max = 89, .symbol = "AIL_add_apply_environment_event_step_v8" },
            .{ .name = "AIL_add_cache_sounds_event_step", .stack_size = 12, .ver = 80 },
            .{ .name = "AIL_add_comment_event_step", .stack_size = 8, .ver = 80 },
            // v8 form @32 (8-arg); v9 adds two trailing args (@40).
            .{ .name = "AIL_add_control_sounds_event_step", .stack_size = 40, .ver = 90 },
            .{ .name = "AIL_add_control_sounds_event_step", .stack_size = 32, .ver = 80, .ver_max = 89, .symbol = "AIL_add_control_sounds_event_step_v8" },
            // v8 form @16 (4-arg); v9 adds a trailing S32 (@20).
            .{ .name = "AIL_add_persist_preset_event_step", .stack_size = 20, .ver = 90 },
            .{ .name = "AIL_add_persist_preset_event_step", .stack_size = 16, .ver = 80, .ver_max = 89, .symbol = "AIL_add_persist_preset_event_step_v8" },
            .{ .name = "AIL_add_sound_limit_event_step", .stack_size = 12, .ver = 90 },
            .{ .name = "AIL_add_sound_limit_event_step", .stack_size = 8, .ver = 80, .ver_max = 80, .symbol = "AIL_add_sound_limit_event_step_v8" },
            // v8 form @76 (19-arg); v9 adds five trailing args (@96).
            .{ .name = "AIL_add_start_sound_event_step", .stack_size = 96, .ver = 90 },
            .{ .name = "AIL_add_start_sound_event_step", .stack_size = 76, .ver = 80, .ver_max = 89, .symbol = "AIL_add_start_sound_event_step_v8" },
            .{ .name = "AIL_add_uncache_sounds_event_step", .stack_size = 12, .ver = 80 },
            .{ .name = "AIL_apply_environment_preset", .stack_size = 12, .ver = 80 },
            .{ .name = "AIL_apply_sound_preset", .stack_size = 12, .ver = 80 },
            .{ .name = "AIL_close_event", .stack_size = 4, .ver = 80 },
            .{ .name = "AIL_close_soundbank", .stack_size = 4, .ver = 80 },
            .{ .name = "AIL_create_event", .stack_size = 0, .ver = 80 },
            .{ .name = "AIL_debug", .stack_size = 4, .ver = 80, .cdecl = true },
            .{ .name = "AIL_debug_log", .stack_size = 4, .ver = 80, .cdecl = true },
            .{ .name = "AIL_enumerate_environment_presets", .stack_size = 16, .ver = 80 },
            .{ .name = "AIL_enumerate_events", .stack_size = 16, .ver = 80 },
            .{ .name = "AIL_enumerate_filter_properties", .stack_size = 12, .ver = 70 },
            .{ .name = "AIL_enumerate_filter_sample_properties", .stack_size = 12, .ver = 70 },
            .{ .name = "AIL_enumerate_output_filter_driver_properties", .stack_size = 12, .ver = 70 },
            .{ .name = "AIL_enumerate_output_filter_sample_properties", .stack_size = 12, .ver = 70 },
            .{ .name = "AIL_enumerate_sample_stage_properties", .stack_size = 16, .ver = 70 },
            .{ .name = "AIL_enumerate_sound_assets", .stack_size = 12, .ver = 80 },
            .{ .name = "AIL_enumerate_sound_presets", .stack_size = 16, .ver = 80 },
            .{ .name = "AIL_file_type_named", .stack_size = 12, .ver = 70 },
            .{ .name = "AIL_filter_property", .stack_size = 20, .ver = 70 },
            // @8 (2-arg) across all of v8 and v9.
            .{ .name = "AIL_find_marker_in_list", .stack_size = 8, .ver = 80, .symbol = "AIL_find_marker_in_list_v8" },
            // @4 (single F32) form spans 6.x-8.x (confirmed in the 6.1 and 7.x DLLs).
            .{ .name = "AIL_ftoa", .stack_size = 4, .ver = 70, .ver_max = 80, .symbol = "AIL_ftoa_v8" },
            .{ .name = "AIL_get_event_contents", .stack_size = 12, .ver = 80 },
            .{ .name = "AIL_get_marker_list", .stack_size = 8, .ver = 80 },
            // v8 form @8 (2-arg); v9 dropped the second arg (@4).
            .{ .name = "AIL_get_soundbank_filename", .stack_size = 4, .ver = 90 },
            .{ .name = "AIL_get_soundbank_filename", .stack_size = 8, .ver = 80, .ver_max = 89, .symbol = "AIL_get_soundbank_filename_v8" },
            .{ .name = "AIL_get_soundbank_mem_usage", .stack_size = 4, .ver = 80 },
            .{ .name = "AIL_indent", .stack_size = 4, .ver = 80, .cdecl = true },
            .{ .name = "AIL_mem_close", .stack_size = 12, .ver = 80 },
            .{ .name = "AIL_mem_create", .stack_size = 0, .ver = 80 },
            .{ .name = "AIL_mem_create_from_existing", .stack_size = 8, .ver = 80 },
            .{ .name = "AIL_mem_error", .stack_size = 4, .ver = 80 },
            .{ .name = "AIL_mem_open", .stack_size = 8, .ver = 80 },
            .{ .name = "AIL_mem_pos", .stack_size = 4, .ver = 80 },
            .{ .name = "AIL_mem_printc", .stack_size = 8, .ver = 80 },
            .{ .name = "AIL_mem_printf", .stack_size = 8, .ver = 80, .cdecl = true },
            .{ .name = "AIL_mem_prints", .stack_size = 8, .ver = 80 },
            .{ .name = "AIL_mem_read", .stack_size = 12, .ver = 80 },
            .{ .name = "AIL_mem_seek", .stack_size = 8, .ver = 80 },
            .{ .name = "AIL_mem_size", .stack_size = 4, .ver = 80 },
            .{ .name = "AIL_mem_write", .stack_size = 12, .ver = 80 },
            .{ .name = "AIL_next_event_step", .stack_size = 16, .ver = 80 },
            .{ .name = "AIL_open_soundbank", .stack_size = 8, .ver = 90 },
            .{ .name = "AIL_open_soundbank", .stack_size = 4, .ver = 80, .ver_max = 80, .symbol = "AIL_open_soundbank_v8" },
            .{ .name = "AIL_output_filter_driver_property", .stack_size = 20, .ver = 70 },
            .{ .name = "AIL_platform_property", .stack_size = 20, .ver = 80 },
            .{ .name = "AIL_register_falloff_function_callback", .stack_size = 8, .ver = 80 },
            // @8 (2-arg) form spans 6.x-8.x (confirmed in the 6.1 and 7.x DLLs).
            .{ .name = "AIL_register_trace_callback", .stack_size = 8, .ver = 70, .ver_max = 80, .symbol = "AIL_register_trace_callback_v8" },
            .{ .name = "AIL_sample_51_volume_levels", .stack_size = 28, .ver = 80 },
            .{ .name = "AIL_sample_51_volume_pan", .stack_size = 24, .ver = 80 },
            .{ .name = "AIL_sample_buffer_available", .stack_size = 4, .ver = 80 },
            .{ .name = "AIL_sample_buffer_count", .stack_size = 4, .ver = 80 },
            .{ .name = "AIL_sample_channel_count", .stack_size = 8, .ver = 80 },
            .{ .name = "AIL_sample_loop_block", .stack_size = 12, .ver = 80 },
            .{ .name = "AIL_sample_output_levels", .stack_size = 20, .ver = 80 },
            .{ .name = "AIL_sample_playback_delay", .stack_size = 4, .ver = 80 },
            .{ .name = "AIL_sample_playback_rate_factor", .stack_size = 4, .ver = 80 },
            .{ .name = "AIL_sample_speaker_scale_factors", .stack_size = 16, .ver = 80 },
            // Arity dips in v7: 6.x and 8.x+ take the 7-arg @28 form; v7 takes a
            // 6-arg @24 form.
            .{ .name = "AIL_sample_stage_property", .stack_size = 24, .ver = 70, .ver_max = 79, .symbol = "AIL_sample_stage_property_v7" },
            .{ .name = "AIL_sample_stage_property", .stack_size = 28, .ver = 80 },
            .{ .name = "AIL_set_sample_51_volume_levels", .stack_size = 28, .ver = 80 },
            .{ .name = "AIL_set_sample_51_volume_pan", .stack_size = 24, .ver = 80 },
            .{ .name = "AIL_set_sample_buffer_count", .stack_size = 8, .ver = 80 },
            .{ .name = "AIL_set_sample_is_3D", .stack_size = 8, .ver = 80 },
            .{ .name = "AIL_set_sample_playback_delay", .stack_size = 8, .ver = 80 },
            .{ .name = "AIL_set_sample_playback_rate_factor", .stack_size = 8, .ver = 80 },
            .{ .name = "AIL_set_sample_speaker_scale_factors", .stack_size = 16, .ver = 80 },
            .{ .name = "AIL_sound_asset_filename", .stack_size = 12, .ver = 80, .ver_max = 80, .symbol = "AIL_sound_asset_filename_v8" },
            .{ .name = "AIL_stricmp", .stack_size = 8, .ver = 80 },
            .{ .name = "AIL_strnicmp", .stack_size = 12, .ver = 80 },
            .{ .name = "AIL_sys_debug", .stack_size = 4, .ver = 80, .cdecl = true },
            .{ .name = "AIL_unapply_environment_preset", .stack_size = 12, .ver = 80 },
            .{ .name = "AIL_unapply_sound_preset", .stack_size = 12, .ver = 80 },
            .{ .name = "AIL_IO_thread_handle", .stack_size = 4, .ver = 90 },
            .{ .name = "AIL_add_clear_state_event_step", .stack_size = 4, .ver = 90 },
            .{ .name = "AIL_add_exec_event_event_step", .stack_size = 8, .ver = 90 },
            .{ .name = "AIL_add_ramp_event_step", .stack_size = 32, .ver = 90 },
            .{ .name = "AIL_add_setblend_event_step", .stack_size = 36, .ver = 90 },
            .{ .name = "AIL_apply_raw_environment_preset", .stack_size = 8, .ver = 80 },
            .{ .name = "AIL_apply_raw_sound_preset", .stack_size = 8, .ver = 80 },
            .{ .name = "AIL_configure_logging", .stack_size = 12, .ver = 90 },
            .{ .name = "AIL_file_callbacks", .stack_size = 16, .ver = 90 },
            .{ .name = "AIL_file_read_info", .stack_size = 16, .ver = 90 },
            .{ .name = "AIL_file_size_info", .stack_size = 12, .ver = 90 },
            .{ .name = "AIL_find_environment_preset", .stack_size = 8, .ver = 80 },
            .{ .name = "AIL_find_sound_preset", .stack_size = 8, .ver = 80 },
            .{ .name = "AIL_get_soundbank_name", .stack_size = 4, .ver = 90 },
            .{ .name = "AIL_get_time", .stack_size = 0, .ver = 90 },
            .{ .name = "AIL_mem_alloc_lock_info", .stack_size = 12, .ver = 90 },
            .{ .name = "AIL_ms_count64", .stack_size = 0, .ver = 90 },
            .{ .name = "AIL_ms_to_time", .stack_size = 8, .ver = 90 },
            .{ .name = "AIL_resolve_raw_environment_preset", .stack_size = 8, .ver = 90 },
            .{ .name = "AIL_resolve_raw_sound_preset", .stack_size = 12, .ver = 90 },
            .{ .name = "AIL_sample_loaded_len", .stack_size = 4, .ver = 90 },
            .{ .name = "AIL_sample_ms_lookup", .stack_size = 12, .ver = 90 },
            .{ .name = "AIL_sleep", .stack_size = 4, .ver = 90 },
            .{ .name = "AIL_sound_asset_info", .stack_size = 16, .ver = 90 },
            .{ .name = "AIL_stream_filled_percent", .stack_size = 4, .ver = 90 },
            .{ .name = "AIL_time_to_ms", .stack_size = 8, .ver = 90 },
            .{ .name = "AIL_timer_thread_handle", .stack_size = 4, .ver = 90 },
            .{ .name = "AIL_unapply_raw_environment_preset", .stack_size = 8, .ver = 80 },
            .{ .name = "AIL_unapply_raw_sound_preset", .stack_size = 8, .ver = 80 },
            .{ .name = "AIL_us_count64", .stack_size = 0, .ver = 90 },
            .{ .name = "AIL_set_sample_id", .stack_size = 8, .ver = 90 },
            .{ .name = "AIL_sample_id", .stack_size = 4, .ver = 90 },
            .{ .name = "AIL_set_sample_bus", .stack_size = 8, .ver = 90 },
            .{ .name = "AIL_sample_bus", .stack_size = 4, .ver = 90 },
            .{ .name = "AIL_set_sample_level_mask", .stack_size = 8, .ver = 90 },
            .{ .name = "AIL_sample_level_mask", .stack_size = 4, .ver = 90 },
            .{ .name = "AIL_set_sample_3D_spread", .stack_size = 8, .ver = 90 },
            .{ .name = "AIL_allocate_bus", .stack_size = 4, .ver = 90 },
            .{ .name = "AIL_free_all_busses", .stack_size = 4, .ver = 90 },
            .{ .name = "AIL_bus_sample_handle", .stack_size = 8, .ver = 90 },
            .{ .name = "AIL_enable_limiter", .stack_size = 8, .ver = 90 },
            .{ .name = "AIL_bus_enable_limiter", .stack_size = 12, .ver = 90 },
            .{ .name = "AIL_install_bus_compressor", .stack_size = 16, .ver = 90 },
            .{ .name = "AIL_digital_mixed_samples", .stack_size = 4, .ver = 90 },
            .{ .name = "AIL_register_mix_callback", .stack_size = 8, .ver = 90 },
            .{ .name = "AIL_end_fade_sample", .stack_size = 4, .ver = 90 },
            .{ .name = "AIL_sample_mixed_ms", .stack_size = 4, .ver = 90 },
            .{ .name = "AIL_sample_schedule_time", .stack_size = 4, .ver = 90 },
            .{ .name = "AIL_schedule_start_sample", .stack_size = 12, .ver = 90 },
            .{ .name = "AIL_set_sample_loop_samples", .stack_size = 12, .ver = 90 },
            .{ .name = "AIL_push_system_state", .stack_size = 12, .ver = 90 },
            .{ .name = "AIL_pop_system_state", .stack_size = 8, .ver = 90 },
            .{ .name = "AIL_system_state_level", .stack_size = 4, .ver = 90 },
            .{ .name = "AIL_set_async_callbacks", .stack_size = 28, .ver = 90 },
            .{ .name = "AIL_start_sample_group", .stack_size = 12, .ver = 90 },
            .{ .name = "AIL_stop_sample_group", .stack_size = 12, .ver = 90 },
            .{ .name = "AIL_resume_sample_group", .stack_size = 12, .ver = 90 },
            .{ .name = "AIL_end_sample_group", .stack_size = 8, .ver = 90 },
            .{ .name = "AIL_set_sample_3D_volume_falloff", .stack_size = 12, .ver = 90 },
            .{ .name = "AIL_set_sample_3D_exclusion_falloff", .stack_size = 12, .ver = 90 },
            .{ .name = "AIL_set_sample_3D_lowpass_falloff", .stack_size = 12, .ver = 90 },
            .{ .name = "AIL_set_sample_3D_spread_falloff", .stack_size = 12, .ver = 90 },
            .{ .name = "AIL_set_sample_3D_position_segments", .stack_size = 12, .ver = 90 },
            .{ .name = "AIL_enqueue_event_start", .stack_size = 0, .ver = 90 },
            .{ .name = "AIL_enqueue_event_cancel", .stack_size = 4, .ver = 90 },
            .{ .name = "AIL_enqueue_event_context", .stack_size = 8, .ver = 90 },
            .{ .name = "AIL_enqueue_event_end_named", .stack_size = 8, .ver = 90 },
            .{ .name = "AIL_enqueue_event_selection", .stack_size = 8, .ver = 90 },
            .{ .name = "AIL_enqueue_event_filter", .stack_size = 12, .ver = 90 },
            .{ .name = "AIL_enqueue_event_variablef", .stack_size = 12, .ver = 90 },
            .{ .name = "AIL_enqueue_event_buffer", .stack_size = 16, .ver = 90 },
            .{ .name = "AIL_enqueue_event_position", .stack_size = 16, .ver = 90 },
            .{ .name = "AIL_enqueue_event_velocity", .stack_size = 20, .ver = 90 },
            .{ .name = "AIL_event_system_command_queue_remaining", .stack_size = 0, .ver = 90 },
            .{ .name = "AIL_set_event_settings", .stack_size = 4, .ver = 90 },
            .{ .name = "AIL_set_event_sample_functions", .stack_size = 8, .ver = 90 },
            .{ .name = "AIL_add_enable_limit_event_step", .stack_size = 8, .ver = 90 },
            .{ .name = "AIL_add_move_var_event_step", .stack_size = 20, .ver = 90 },
            .{ .name = "AIL_add_set_lfo_event_step", .stack_size = 40, .ver = 90 },
            // Miles 9.x event-system C-ABI (the 9.x SDK aliases AIL_* event names
            // onto these). Real mss32.dll 9.x exports the Miles* set.
            // @16 (4-arg) in both v8 and v9 — the default covers both.
            .{ .name = "MilesStartupEventSystem", .stack_size = 16, .ver = 80 },
            .{ .name = "MilesShutdownEventSystem", .stack_size = 0, .ver = 80 },
            .{ .name = "MilesAddEventSystem", .stack_size = 4, .ver = 90 },
            .{ .name = "MilesGetEventSystemState", .stack_size = 8, .ver = 90 },
            .{ .name = "MilesGetEventSystemState", .stack_size = 4, .ver = 80, .ver_max = 80, .symbol = "MilesGetEventSystemState_v8" },
            .{ .name = "MilesSetVarI", .stack_size = 12, .ver = 90 },
            .{ .name = "MilesSetVarF", .stack_size = 12, .ver = 90 },
            .{ .name = "MilesGetVarI", .stack_size = 12, .ver = 90 },
            .{ .name = "MilesGetVarF", .stack_size = 12, .ver = 90 },
            .{ .name = "MilesEnqueueEvent", .stack_size = 24, .ver = 80 },
            .{ .name = "MilesEnqueueEventContext", .stack_size = 28, .ver = 90 },
            .{ .name = "MilesEnqueueEventByName", .stack_size = 4, .ver = 90 },
            .{ .name = "MilesBeginEventQueueProcessing", .stack_size = 0, .ver = 80 },
            .{ .name = "MilesCompleteEventQueueProcessing", .stack_size = 0, .ver = 80 },
            .{ .name = "MilesClearEventQueue", .stack_size = 0, .ver = 80 },
            .{ .name = "MilesStartSoundInstance", .stack_size = 32, .ver = 80 },
            .{ .name = "MilesStopSoundInstances", .stack_size = 12, .ver = 80 },
            .{ .name = "MilesPauseSoundInstances", .stack_size = 12, .ver = 80 },
            .{ .name = "MilesResumeSoundInstances", .stack_size = 12, .ver = 80 },
            .{ .name = "MilesEnumerateSoundInstances", .stack_size = 28, .ver = 90 },
            .{ .name = "MilesEnumerateSoundInstances", .stack_size = 24, .ver = 80, .ver_max = 80, .symbol = "MilesEnumerateSoundInstances_v8" },
            .{ .name = "MilesEnumeratePresetPersists", .stack_size = 12, .ver = 90 },
            .{ .name = "MilesEnumeratePresetPersists", .stack_size = 8, .ver = 80, .ver_max = 80, .symbol = "MilesEnumeratePresetPersists_v8" },
            .{ .name = "MilesSetSoundStartOffset", .stack_size = 12, .ver = 90 },
            .{ .name = "MilesSetSoundLabelLimits", .stack_size = 8, .ver = 90 },
            .{ .name = "MilesSetSoundLabelLimits", .stack_size = 4, .ver = 80, .ver_max = 80, .symbol = "MilesSetSoundLabelLimits_v8" },
            .{ .name = "MilesAddSoundBank", .stack_size = 8, .ver = 90 },
            .{ .name = "MilesAddSoundBank", .stack_size = 4, .ver = 80, .ver_max = 80, .symbol = "MilesAddSoundBank_v8" },
            .{ .name = "MilesReleaseSoundBank", .stack_size = 4, .ver = 80 },
            .{ .name = "MilesFindEvent", .stack_size = 8, .ver = 80 },
            .{ .name = "MilesGetEventLength", .stack_size = 4, .ver = 90 },
            .{ .name = "MilesTextDumpEventSystem", .stack_size = 0, .ver = 80 },
            .{ .name = "MilesRegisterRand", .stack_size = 4, .ver = 80 },
            .{ .name = "MilesSetEventErrorCallback", .stack_size = 4, .ver = 80 },
            .{ .name = "MilesEventSetAuditionFunctions", .stack_size = 4, .ver = 90, .cdecl = true },
            .{ .name = "MilesGetBankFunctions", .stack_size = 0, .ver = 90 },
            .{ .name = "MilesSetBankFunctions", .stack_size = 4, .ver = 80 },
            .{ .name = "MilesUseTelemetry", .stack_size = 4, .ver = 90 },
            .{ .name = "MilesUseTmLite", .stack_size = 4, .ver = 90 },
            .{ .name = "MilesAsyncStartup", .stack_size = 0, .ver = 90 },
            .{ .name = "MilesAsyncShutdown", .stack_size = 0, .ver = 90 },
            .{ .name = "MilesAsyncFileRead", .stack_size = 4, .ver = 90 },
            .{ .name = "MilesAsyncFileCancel", .stack_size = 4, .ver = 90 },
            .{ .name = "MilesAsyncFileStatus", .stack_size = 8, .ver = 90 },
            .{ .name = "MilesAsyncSetPaused", .stack_size = 4, .ver = 90 },
            .{ .name = "MilesRequeueAsyncs", .stack_size = 0, .ver = 90 },
            // Quick-API mem loader with a filename format hint (6.x onward).
            .{ .name = "AIL_quick_load_named_mem", .stack_size = 12, .ver = 70, .ver_max = 70 },
            // 6.x-only embedded-library + sample-attribute exports (gone by 7.0).
            .{ .name = "AIL_open_library", .stack_size = 8, .ver = 60, .ver_max = 69 },
            .{ .name = "AIL_close_library", .stack_size = 4, .ver = 60, .ver_max = 69 },
            .{ .name = "AIL_library_resource_filename", .stack_size = 16, .ver = 60, .ver_max = 69 },
            .{ .name = "AIL_load_sample_attributes", .stack_size = 8, .ver = 60, .ver_max = 69 },
            .{ .name = "AIL_save_sample_attributes", .stack_size = 8, .ver = 60, .ver_max = 69 },
        };
        // Emit one PE export per active target, as the MSVC-decorated stdcall
        // name `_NAME@stack`, via @export rather than `export fn`. A bare
        // `export fn` would ALSO leak the underscore-less `NAME@stack` symbol,
        // doubling the table and shifting the alphabetical ordinal numbering
        // away from the reference DLL. With @export only the decorated name is
        // emitted; Zig appends the `@stack` suffix from each function's own
        // arity, so the per-version arity variants resolve automatically. The
        // function is located by name (or `symbol` override) across the api
        // modules plus this file itself (which owns DllMain) — none of which
        // import this one, so there is no cycle.
        const mods = .{
            @This(),
            @import("api/digital.zig"),
            @import("api/3d.zig"),
            @import("api/stream.zig"),
            @import("api/quick.zig"),
            @import("api/redbook.zig"),
            @import("api/timer.zig"),
            @import("api/file.zig"),
            @import("api/input.zig"),
            @import("api/midi.zig"),
            @import("api/dls.zig"),
            @import("api/rib.zig"),
            @import("api/filter.zig"),
            @import("api/memory.zig"),
            @import("api/v7.zig"),
            @import("api/v8.zig"),
            @import("api/v9.zig"),
            @import("api/miles.zig"),
            @import("api/legacy.zig"),
        };
        // API families dropped wholesale in MSS 8.0. The 8.0e/9.1d DLLs export
        // none of these symbols (all are present through 7.0k), so emitting them
        // would bloat the export table beyond the reference. Each token below was
        // verified to occur in zero 8.0e/9.1d exports and >0 7.0k exports, so a
        // substring match is safe and only suppresses these from 8.0 on. Covered:
        // the Quick API, Redbook (CD audio), the whole XMIDI/MIDI-sequencer stack
        // (sequences, channels, MIDI/XMIDI drivers, midiOut, the MIDI callback
        // registrations, the software wave synthesizer) and the DLS API.
        const removed_at_80 = [_][]const u8{
            "redbook",           "quick",              "sequence",
            "DLS",               "midiOut",            "XMIDI",
            "midi_driver",       "register_beat",      "register_trigger",
            "register_sequence", "register_timbre",    "register_prefix",
            "register_ICA",      "channel_notes",      "lock_channel",
            "release_channel",   "send_channel_voice", "send_sysex",
            "controller_value",  "branch_index",       "wave_synthesizer",
            "map_sequence",      "true_sequence",
        };
        // Export names that appear in NO reference DLL (3.6a..9.1d) and nowhere in
        // the 9.3b SDK (headers + source). These table entries were mistakes: no
        // real Miles release ever exported them, so they must not appear in any
        // version's export table. Their implementations remain callable internally
        // and from tests; they are simply never emitted as PE exports.
        const never_export = [_][]const u8{
            "AIL_pause_sample",
            "AIL_open_ASI_provider",
            "AIL_close_ASI_provider",
            "AIL_ASI_provider_attribute",
            "AIL_3D_sample_ms_position",
            "AIL_set_3D_sample_ms_position",
            "AIL_set_event_sample_functions",
            "AIL_set_filter_attribute",
            "AIL_set_sample_filter",
            "AIL_set_mem_callbacks",
            "AIL_set_timer_user_data",
            // Wrong-name duplicates: a real Miles export exists under a different
            // name (open_XMIDI_driver, quick_halt, DLS_unload, open_input/
            // close_input/get_input_info, ...). We already export the correct
            // names (parity MISSING stays 0); these aliases are emitted by no
            // real release.
            "AIL_open_midi_driver",
            "AIL_close_midi_driver",
            "AIL_quick_stop",
            "AIL_DLS_unload_file",
            "AIL_input_open",
            "AIL_input_close",
            "AIL_pause_sequence",
            "AIL_3D_sample_float_distances",
            "AIL_set_3D_sample_float_distances",
            "AIL_open_stream_by_sample",
            "AIL_open_stream_ex",
            "AIL_start_sample_at",
            "AIL_get_DirectSound3D_info",
            // The v6 "resource library" and sample-attribute persistence names,
            // and the filter/stage *_attribute / *_preference spellings: none
            // appear in any reference DLL or SDK header (the real DSP-property
            // surface uses *_property, handled elsewhere).
            "AIL_open_library",
            "AIL_close_library",
            "AIL_library_resource_filename",
            "AIL_load_sample_attributes",
            "AIL_save_sample_attributes",
            "AIL_sample_stage_attribute",
            "AIL_set_sample_stage_preference",
            "AIL_output_filter_driver_attribute",
            "AIL_set_output_filter_driver_preference",
            "AIL_enumerate_sample_stage_attributes",
            "AIL_enumerate_output_filter_driver_attributes",
            "AIL_enumerate_output_filter_sample_attributes",
        };
        for (targets) |t| {
            if (openmiles.mss_version < t.ver or openmiles.mss_version > t.ver_max) continue;
            const dropped = openmiles.mss_version >= 80 and for (removed_at_80) |tok| {
                if (std.mem.indexOf(u8, t.name, tok) != null) break true;
            } else false;
            if (dropped) continue;
            const spurious = for (never_export) |n| {
                if (std.mem.eql(u8, t.name, n)) break true;
            } else false;
            if (spurious) continue;
            const fname = t.symbol orelse t.name;
            const exp_name = if (t.cdecl) t.name else "_" ++ t.name;
            for (mods) |m| {
                if (@hasDecl(m, fname)) {
                    @export(&@field(m, fname), .{ .name = exp_name, .linkage = .strong });
                    break;
                }
            }
        }
        // (The CRT entry DllMainCRTStartup is the PE entry point via the header,
        // not an export — real mss32.dll does not export it, so neither do we.)
        // Variadic functions use callconv(.c), generating `_FuncName` in COFF (not `_FuncName@N`).
        // They are NOT in the stdcall targets loop, so they need explicit /EXPORT renames so the
        // DLL export table contains the bare name (AIL_debug_printf) rather than _AIL_debug_printf.
        // The linker automatically prepends `_` to the symbol reference in /EXPORT:name=symbol,
        // so we use the bare name (without leading underscore) as the symbol.
        // AIL_sprintf was introduced in 5.0 (3.6a exports neither it nor
        // AIL_debug_printf); AIL_debug_printf runs 5.0..8.0 and is gone by 9.1d.
        if (openmiles.mss_version >= 50) {
            asm (".section .drectve\n .ascii \" /EXPORT:AIL_sprintf=AIL_sprintf\"\n .text\n");
        }
        if (openmiles.mss_version >= 50 and openmiles.mss_version <= 80) {
            asm (".section .drectve\n .ascii \" /EXPORT:AIL_debug_printf=AIL_debug_printf\"\n .text\n");
        }
        // `stream_background`: an undocumented internal symbol that leaked into
        // the 6.1-6.6 export tables. Its decoration varies *within* a minor
        // version: fastcall `@stream_background@0` in 6.1 and 6.5a-c, but
        // undecorated `stream_background` from 6.5d onward (and all of 6.6),
        // confirming it is an accidental export, not an API. Our canonical 6.5
        // reference is 6.5h (a 6.5d+ patch), which exports the undecorated form
        // only, so for v65 we emit just that and match it exactly.
        if (openmiles.mss_version == 61) {
            asm (".section .drectve\n .ascii \" /EXPORT:@stream_background@0=mss_stream_background_stub\"\n .text\n");
        } else if (openmiles.mss_version == 65) {
            asm (".section .drectve\n .ascii \" /EXPORT:stream_background=mss_stream_background_stub\"\n .text\n");
        } else if (openmiles.mss_version == 66) {
            asm (".section .drectve\n .ascii \" /EXPORT:stream_background=mss_stream_background_stub\"\n .text\n");
        }
    }
}
